-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_19ea_csc_0_AXIvideo2MultiPixStream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    s_axis_video_TVALID : IN STD_LOGIC;
    s_axis_video_TREADY : OUT STD_LOGIC;
    s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_in_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    stream_in_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_in_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_in_full_n : IN STD_LOGIC;
    stream_in_write : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    HwReg_width_c3_din : OUT STD_LOGIC_VECTOR (10 downto 0);
    HwReg_width_c3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_width_c3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_width_c3_full_n : IN STD_LOGIC;
    HwReg_width_c3_write : OUT STD_LOGIC;
    HwReg_height_c5_din : OUT STD_LOGIC_VECTOR (10 downto 0);
    HwReg_height_c5_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_height_c5_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_height_c5_full_n : IN STD_LOGIC;
    HwReg_height_c5_write : OUT STD_LOGIC );
end;


architecture behav of bd_19ea_csc_0_AXIvideo2MultiPixStream is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal HwReg_width_c3_blk_n : STD_LOGIC;
    signal HwReg_height_c5_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal cond_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cond_reg_342 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_reg_unsigned_short_s_fu_257_ap_return : STD_LOGIC_VECTOR (10 downto 0);
    signal rows_reg_347 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_reg_unsigned_short_s_fu_262_ap_return : STD_LOGIC_VECTOR (10 downto 0);
    signal cols_reg_352 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_4_fu_278_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_4_reg_363 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_s_axis_video_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_axi_data_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_axi_data_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_axi_last_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_axi_last_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_stream_in_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_stream_in_write : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_s_axis_video_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_eol_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_eol_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_axi_data_14_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_axi_data_14_out_ap_vld : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_start : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_done : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_idle : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_ready : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_s_axis_video_TREADY : STD_LOGIC;
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_axi_data_4_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_axi_data_4_out_ap_vld : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_257_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_257_ap_done : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_257_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_257_ap_ready : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_257_ap_ce : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_reg_unsigned_short_s_fu_262_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_262_ap_done : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_262_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_262_ap_ready : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_262_ap_ce : STD_LOGIC;
    signal sof_reg_150 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal axi_last_2_reg_164 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal axi_data_13_fu_96 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_reg_unsigned_short_s_fu_257_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm_state3 : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_262_ap_start_reg : STD_LOGIC := '0';
    signal i_fu_100 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal HwReg_height_c5_write_local : STD_LOGIC;
    signal HwReg_width_c3_write_local : STD_LOGIC;
    signal icmp_ln541_fu_273_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal regslice_both_s_axis_video_V_data_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal s_axis_video_TVALID_int_regslice : STD_LOGIC;
    signal s_axis_video_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_axis_video_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_s_axis_video_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_s_axis_video_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_user_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_video_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_last_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_video_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_id_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_video_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_video_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_dest_V_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bd_19ea_csc_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        axi_data_out_ap_vld : OUT STD_LOGIC;
        axi_last_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        axi_last_out_ap_vld : OUT STD_LOGIC );
    end component;


    component bd_19ea_csc_0_AXIvideo2MultiPixStream_Pipeline_loop_width IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        stream_in_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        stream_in_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_in_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_in_full_n : IN STD_LOGIC;
        stream_in_write : OUT STD_LOGIC;
        sof_4 : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_last_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_13 : IN STD_LOGIC_VECTOR (23 downto 0);
        cols : IN STD_LOGIC_VECTOR (10 downto 0);
        cond : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        eol_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        eol_out_ap_vld : OUT STD_LOGIC;
        axi_data_14_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        axi_data_14_out_ap_vld : OUT STD_LOGIC );
    end component;


    component bd_19ea_csc_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        axi_data_14_reload : IN STD_LOGIC_VECTOR (23 downto 0);
        eol_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        axi_data_4_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        axi_data_4_out_ap_vld : OUT STD_LOGIC );
    end component;


    component bd_19ea_csc_0_reg_unsigned_short_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        d : IN STD_LOGIC_VECTOR (10 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component bd_19ea_csc_0_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176 : component bd_19ea_csc_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID_int_regslice,
        s_axis_video_TDATA => s_axis_video_TDATA_int_regslice,
        s_axis_video_TREADY => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP_int_regslice,
        s_axis_video_TSTRB => s_axis_video_TSTRB_int_regslice,
        s_axis_video_TUSER => s_axis_video_TUSER_int_regslice,
        s_axis_video_TLAST => s_axis_video_TLAST_int_regslice,
        s_axis_video_TID => s_axis_video_TID_int_regslice,
        s_axis_video_TDEST => s_axis_video_TDEST_int_regslice,
        axi_data_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_axi_data_out,
        axi_data_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_axi_data_out_ap_vld,
        axi_last_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_axi_last_out,
        axi_last_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_axi_last_out_ap_vld);

    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196 : component bd_19ea_csc_0_AXIvideo2MultiPixStream_Pipeline_loop_width
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID_int_regslice,
        stream_in_din => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_stream_in_din,
        stream_in_num_data_valid => ap_const_lv5_0,
        stream_in_fifo_cap => ap_const_lv5_0,
        stream_in_full_n => stream_in_full_n,
        stream_in_write => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_stream_in_write,
        sof_4 => sof_reg_150,
        axi_last_2 => axi_last_2_reg_164,
        axi_data_13 => axi_data_13_fu_96,
        cols => cols_reg_352,
        cond => cond_reg_342,
        s_axis_video_TDATA => s_axis_video_TDATA_int_regslice,
        s_axis_video_TREADY => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP_int_regslice,
        s_axis_video_TSTRB => s_axis_video_TSTRB_int_regslice,
        s_axis_video_TUSER => s_axis_video_TUSER_int_regslice,
        s_axis_video_TLAST => s_axis_video_TLAST_int_regslice,
        s_axis_video_TID => s_axis_video_TID_int_regslice,
        s_axis_video_TDEST => s_axis_video_TDEST_int_regslice,
        eol_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_eol_out,
        eol_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_eol_out_ap_vld,
        axi_data_14_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_axi_data_14_out,
        axi_data_14_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_axi_data_14_out_ap_vld);

    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225 : component bd_19ea_csc_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_start,
        ap_done => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_done,
        ap_idle => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_idle,
        ap_ready => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_ready,
        s_axis_video_TVALID => s_axis_video_TVALID_int_regslice,
        axi_data_14_reload => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_axi_data_14_out,
        eol_reload => grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_eol_out,
        s_axis_video_TDATA => s_axis_video_TDATA_int_regslice,
        s_axis_video_TREADY => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP_int_regslice,
        s_axis_video_TSTRB => s_axis_video_TSTRB_int_regslice,
        s_axis_video_TUSER => s_axis_video_TUSER_int_regslice,
        s_axis_video_TLAST => s_axis_video_TLAST_int_regslice,
        s_axis_video_TID => s_axis_video_TID_int_regslice,
        s_axis_video_TDEST => s_axis_video_TDEST_int_regslice,
        axi_data_4_out => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_axi_data_4_out,
        axi_data_4_out_ap_vld => grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_axi_data_4_out_ap_vld);

    grp_reg_unsigned_short_s_fu_257 : component bd_19ea_csc_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_s_fu_257_ap_start,
        ap_done => grp_reg_unsigned_short_s_fu_257_ap_done,
        ap_idle => grp_reg_unsigned_short_s_fu_257_ap_idle,
        ap_ready => grp_reg_unsigned_short_s_fu_257_ap_ready,
        ap_ce => grp_reg_unsigned_short_s_fu_257_ap_ce,
        d => p_read,
        ap_return => grp_reg_unsigned_short_s_fu_257_ap_return);

    grp_reg_unsigned_short_s_fu_262 : component bd_19ea_csc_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_s_fu_262_ap_start,
        ap_done => grp_reg_unsigned_short_s_fu_262_ap_done,
        ap_idle => grp_reg_unsigned_short_s_fu_262_ap_idle,
        ap_ready => grp_reg_unsigned_short_s_fu_262_ap_ready,
        ap_ce => grp_reg_unsigned_short_s_fu_262_ap_ce,
        d => p_read1,
        ap_return => grp_reg_unsigned_short_s_fu_262_ap_return);

    regslice_both_s_axis_video_V_data_V_U : component bd_19ea_csc_0_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_axis_video_TDATA,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_data_V_U_ack_in,
        data_out => s_axis_video_TDATA_int_regslice,
        vld_out => s_axis_video_TVALID_int_regslice,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_data_V_U_apdone_blk);

    regslice_both_s_axis_video_V_keep_V_U : component bd_19ea_csc_0_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_axis_video_TKEEP,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_keep_V_U_ack_in,
        data_out => s_axis_video_TKEEP_int_regslice,
        vld_out => regslice_both_s_axis_video_V_keep_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_keep_V_U_apdone_blk);

    regslice_both_s_axis_video_V_strb_V_U : component bd_19ea_csc_0_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_axis_video_TSTRB,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_strb_V_U_ack_in,
        data_out => s_axis_video_TSTRB_int_regslice,
        vld_out => regslice_both_s_axis_video_V_strb_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_strb_V_U_apdone_blk);

    regslice_both_s_axis_video_V_user_V_U : component bd_19ea_csc_0_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_axis_video_TUSER,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_user_V_U_ack_in,
        data_out => s_axis_video_TUSER_int_regslice,
        vld_out => regslice_both_s_axis_video_V_user_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_user_V_U_apdone_blk);

    regslice_both_s_axis_video_V_last_V_U : component bd_19ea_csc_0_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_axis_video_TLAST,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_last_V_U_ack_in,
        data_out => s_axis_video_TLAST_int_regslice,
        vld_out => regslice_both_s_axis_video_V_last_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_last_V_U_apdone_blk);

    regslice_both_s_axis_video_V_id_V_U : component bd_19ea_csc_0_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_axis_video_TID,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_id_V_U_ack_in,
        data_out => s_axis_video_TID_int_regslice,
        vld_out => regslice_both_s_axis_video_V_id_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_id_V_U_apdone_blk);

    regslice_both_s_axis_video_V_dest_V_U : component bd_19ea_csc_0_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_axis_video_TDEST,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_dest_V_U_ack_in,
        data_out => s_axis_video_TDEST_int_regslice,
        vld_out => regslice_both_s_axis_video_V_dest_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln541_fu_273_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_ready = ap_const_logic_1)) then 
                    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_reg_unsigned_short_s_fu_257_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_reg_unsigned_short_s_fu_257_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state3) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_reg_unsigned_short_s_fu_257_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_reg_unsigned_short_s_fu_257_ap_ready = ap_const_logic_1)) then 
                    grp_reg_unsigned_short_s_fu_257_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_reg_unsigned_short_s_fu_262_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_reg_unsigned_short_s_fu_262_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state3) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_reg_unsigned_short_s_fu_262_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_reg_unsigned_short_s_fu_262_ap_ready = ap_const_logic_1)) then 
                    grp_reg_unsigned_short_s_fu_262_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    axi_data_13_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_axi_data_4_out_ap_vld = ap_const_logic_1))) then 
                axi_data_13_fu_96 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_axi_data_4_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_axi_data_out_ap_vld = ap_const_logic_1))) then 
                axi_data_13_fu_96 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_axi_data_out;
            end if; 
        end if;
    end process;

    axi_last_2_reg_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_done = ap_const_logic_1))) then 
                axi_last_2_reg_164 <= ap_const_lv1_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                axi_last_2_reg_164 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_axi_last_out;
            end if; 
        end if;
    end process;

    i_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_100 <= ap_const_lv11_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                i_fu_100 <= i_4_reg_363;
            end if; 
        end if;
    end process;

    sof_reg_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_done = ap_const_logic_1))) then 
                sof_reg_150 <= ap_const_lv1_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                sof_reg_150 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                cols_reg_352 <= grp_reg_unsigned_short_s_fu_262_ap_return;
                rows_reg_347 <= grp_reg_unsigned_short_s_fu_257_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                cond_reg_342 <= cond_fu_246_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                i_4_reg_363 <= i_4_fu_278_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state5, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_done, grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_done, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state7, icmp_ln541_fu_273_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln541_fu_273_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;

    HwReg_height_c5_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_height_c5_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_height_c5_blk_n <= HwReg_height_c5_full_n;
        else 
            HwReg_height_c5_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_height_c5_din <= p_read;
    HwReg_height_c5_write <= HwReg_height_c5_write_local;

    HwReg_height_c5_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_height_c5_write_local <= ap_const_logic_1;
        else 
            HwReg_height_c5_write_local <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_width_c3_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_width_c3_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_width_c3_blk_n <= HwReg_width_c3_full_n;
        else 
            HwReg_width_c3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_width_c3_din <= p_read1;
    HwReg_width_c3_write <= HwReg_width_c3_write_local;

    HwReg_width_c3_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_width_c3_write_local <= ap_const_logic_1;
        else 
            HwReg_width_c3_write_local <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_NS_fsm_state3 <= ap_NS_fsm(2);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_done)
    begin
        if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, HwReg_width_c3_full_n, HwReg_height_c5_full_n)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = HwReg_height_c5_full_n) or (ap_const_logic_0 = HwReg_width_c3_full_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, icmp_ln541_fu_273_p2)
    begin
        if (((icmp_ln541_fu_273_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, icmp_ln541_fu_273_p2)
    begin
        if (((icmp_ln541_fu_273_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    cond_fu_246_p2 <= "1" when (p_read2 = ap_const_lv8_0) else "0";
    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_start <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_ap_start_reg;
    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_start <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_start_reg;
    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_start <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_ap_start_reg;

    grp_reg_unsigned_short_s_fu_257_ap_ce_assign_proc : process(ap_CS_fsm_state4, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_done, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_done = ap_const_logic_1)))) then 
            grp_reg_unsigned_short_s_fu_257_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_257_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_reg_unsigned_short_s_fu_257_ap_start <= grp_reg_unsigned_short_s_fu_257_ap_start_reg;

    grp_reg_unsigned_short_s_fu_262_ap_ce_assign_proc : process(ap_CS_fsm_state4, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_done, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_ap_done = ap_const_logic_1)))) then 
            grp_reg_unsigned_short_s_fu_262_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_262_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_reg_unsigned_short_s_fu_262_ap_start <= grp_reg_unsigned_short_s_fu_262_ap_start_reg;
    i_4_fu_278_p2 <= std_logic_vector(unsigned(i_fu_100) + unsigned(ap_const_lv11_1));
    icmp_ln541_fu_273_p2 <= "1" when (i_fu_100 = rows_reg_347) else "0";
    s_axis_video_TREADY <= regslice_both_s_axis_video_V_data_V_U_ack_in;

    s_axis_video_TREADY_int_regslice_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_s_axis_video_TREADY, grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_s_axis_video_TREADY, grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_s_axis_video_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            s_axis_video_TREADY_int_regslice <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_225_s_axis_video_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            s_axis_video_TREADY_int_regslice <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_s_axis_video_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            s_axis_video_TREADY_int_regslice <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_176_s_axis_video_TREADY;
        else 
            s_axis_video_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    stream_in_din <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_stream_in_din;

    stream_in_write_assign_proc : process(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_stream_in_write, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            stream_in_write <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_196_stream_in_write;
        else 
            stream_in_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
