// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_19ea_csc_0_v_csc_core (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stream_in_dout,
        stream_in_num_data_valid,
        stream_in_fifo_cap,
        stream_in_empty_n,
        stream_in_read,
        height_dout,
        height_num_data_valid,
        height_fifo_cap,
        height_empty_n,
        height_read,
        width_dout,
        width_num_data_valid,
        width_fifo_cap,
        width_empty_n,
        width_read,
        K11_read,
        K12_read,
        K13_read,
        K21_read,
        K22_read,
        K23_read,
        K31_read,
        K32_read,
        K33_read,
        ROffset_read,
        GOffset_read,
        BOffset_read,
        ClampMin_read,
        ClipMax_read,
        stream_csc_din,
        stream_csc_num_data_valid,
        stream_csc_fifo_cap,
        stream_csc_full_n,
        stream_csc_write,
        HwReg_width_c_din,
        HwReg_width_c_num_data_valid,
        HwReg_width_c_fifo_cap,
        HwReg_width_c_full_n,
        HwReg_width_c_write,
        HwReg_height_c_din,
        HwReg_height_c_num_data_valid,
        HwReg_height_c_fifo_cap,
        HwReg_height_c_full_n,
        HwReg_height_c_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] stream_in_dout;
input  [4:0] stream_in_num_data_valid;
input  [4:0] stream_in_fifo_cap;
input   stream_in_empty_n;
output   stream_in_read;
input  [10:0] height_dout;
input  [2:0] height_num_data_valid;
input  [2:0] height_fifo_cap;
input   height_empty_n;
output   height_read;
input  [10:0] width_dout;
input  [2:0] width_num_data_valid;
input  [2:0] width_fifo_cap;
input   width_empty_n;
output   width_read;
input  [15:0] K11_read;
input  [15:0] K12_read;
input  [15:0] K13_read;
input  [15:0] K21_read;
input  [15:0] K22_read;
input  [15:0] K23_read;
input  [15:0] K31_read;
input  [15:0] K32_read;
input  [15:0] K33_read;
input  [9:0] ROffset_read;
input  [9:0] GOffset_read;
input  [9:0] BOffset_read;
input  [7:0] ClampMin_read;
input  [7:0] ClipMax_read;
output  [23:0] stream_csc_din;
input  [4:0] stream_csc_num_data_valid;
input  [4:0] stream_csc_fifo_cap;
input   stream_csc_full_n;
output   stream_csc_write;
output  [10:0] HwReg_width_c_din;
input  [2:0] HwReg_width_c_num_data_valid;
input  [2:0] HwReg_width_c_fifo_cap;
input   HwReg_width_c_full_n;
output   HwReg_width_c_write;
output  [10:0] HwReg_height_c_din;
input  [2:0] HwReg_height_c_num_data_valid;
input  [2:0] HwReg_height_c_fifo_cap;
input   HwReg_height_c_full_n;
output   HwReg_height_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_in_read;
reg stream_csc_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    height_blk_n;
reg    width_blk_n;
reg    HwReg_width_c_blk_n;
reg    HwReg_height_c_blk_n;
reg    ap_block_state1;
wire   [21:0] thr_add_fu_233_p3;
reg   [21:0] thr_add_reg_365;
wire   [21:0] thr_add1_fu_241_p3;
reg   [21:0] thr_add1_reg_370;
wire   [21:0] thr_add3_fu_249_p3;
reg   [21:0] thr_add3_reg_375;
wire   [11:0] add_ln134_fu_261_p2;
reg   [11:0] add_ln134_reg_380;
wire   [11:0] add_ln134_1_fu_271_p2;
reg   [11:0] add_ln134_1_reg_385;
wire    grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start;
wire    grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_done;
wire    grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_idle;
wire    grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_ready;
wire    grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_in_read;
wire   [23:0] grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_csc_din;
wire    grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_csc_write;
reg    grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln134_fu_285_p2;
wire    ap_CS_fsm_state3;
reg   [11:0] y_fu_92;
wire   [11:0] y_3_fu_290_p2;
reg    height_read_local;
reg    HwReg_height_c_write_local;
reg    width_read_local;
reg    HwReg_width_c_write_local;
wire   [11:0] loopWidth_cast_fu_257_p1;
wire   [11:0] height_load_cast_fu_267_p1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start_reg = 1'b0;
#0 y_fu_92 = 12'd0;
end

bd_19ea_csc_0_v_csc_core_Pipeline_VITIS_LOOP_136_2 grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start),
    .ap_done(grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_done),
    .ap_idle(grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_idle),
    .ap_ready(grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_ready),
    .stream_in_dout(stream_in_dout),
    .stream_in_num_data_valid(5'd0),
    .stream_in_fifo_cap(5'd0),
    .stream_in_empty_n(stream_in_empty_n),
    .stream_in_read(grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_in_read),
    .stream_csc_din(grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_csc_din),
    .stream_csc_num_data_valid(5'd0),
    .stream_csc_fifo_cap(5'd0),
    .stream_csc_full_n(stream_csc_full_n),
    .stream_csc_write(grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_csc_write),
    .add_ln134(add_ln134_reg_380),
    .K12_load_cast(K12_read),
    .K13_load_cast(K13_read),
    .K11_load_cast(K11_read),
    .thr_add131_cast(thr_add_reg_365),
    .K22_load_cast(K22_read),
    .K23_load_cast(K23_read),
    .K21_load_cast(K21_read),
    .thr_add62_cast(thr_add1_reg_370),
    .K32_load_cast(K32_read),
    .K33_load_cast(K33_read),
    .K31_load_cast(K31_read),
    .sext_ln134(thr_add3_reg_375),
    .p_read12_cast(ClampMin_read),
    .p_read13_cast(ClipMax_read),
    .ClipMax_read(ClipMax_read),
    .ClampMin_read(ClampMin_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln134_fu_285_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln134_fu_285_p2 == 1'd0))) begin
            grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start_reg <= 1'b1;
        end else if ((grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_ready == 1'b1)) begin
            grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_92 <= 12'd1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln134_fu_285_p2 == 1'd0))) begin
        y_fu_92 <= y_3_fu_290_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln134_1_reg_385 <= add_ln134_1_fu_271_p2;
        add_ln134_reg_380 <= add_ln134_fu_261_p2;
        thr_add1_reg_370[21 : 12] <= thr_add1_fu_241_p3[21 : 12];
        thr_add3_reg_375[21 : 12] <= thr_add3_fu_249_p3[21 : 12];
        thr_add_reg_365[21 : 12] <= thr_add_fu_233_p3[21 : 12];
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_c_blk_n = HwReg_height_c_full_n;
    end else begin
        HwReg_height_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_c_write_local = 1'b1;
    end else begin
        HwReg_height_c_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_c_blk_n = HwReg_width_c_full_n;
    end else begin
        HwReg_width_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_c_write_local = 1'b1;
    end else begin
        HwReg_width_c_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln134_fu_285_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln134_fu_285_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_blk_n = height_empty_n;
    end else begin
        height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        height_read_local = 1'b1;
    end else begin
        height_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_csc_write = grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_csc_write;
    end else begin
        stream_csc_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_read = grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_in_read;
    end else begin
        stream_in_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_blk_n = width_empty_n;
    end else begin
        width_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        width_read_local = 1'b1;
    end else begin
        width_read_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln134_fu_285_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HwReg_height_c_din = height_dout;

assign HwReg_height_c_write = HwReg_height_c_write_local;

assign HwReg_width_c_din = width_dout;

assign HwReg_width_c_write = HwReg_width_c_write_local;

assign add_ln134_1_fu_271_p2 = (height_load_cast_fu_267_p1 + 12'd1);

assign add_ln134_fu_261_p2 = (loopWidth_cast_fu_257_p1 + 12'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (1'b0 == HwReg_height_c_full_n) | (1'b0 == HwReg_width_c_full_n) | (ap_done_reg == 1'b1));
end

assign grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start = grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start_reg;

assign height_load_cast_fu_267_p1 = height_dout;

assign height_read = height_read_local;

assign icmp_ln134_fu_285_p2 = ((y_fu_92 == add_ln134_1_reg_385) ? 1'b1 : 1'b0);

assign loopWidth_cast_fu_257_p1 = width_dout;

assign stream_csc_din = grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_csc_din;

assign thr_add1_fu_241_p3 = {{GOffset_read}, {12'd2048}};

assign thr_add3_fu_249_p3 = {{BOffset_read}, {12'd2048}};

assign thr_add_fu_233_p3 = {{ROffset_read}, {12'd2048}};

assign width_read = width_read_local;

assign y_3_fu_290_p2 = (y_fu_92 + 12'd1);

always @ (posedge ap_clk) begin
    thr_add_reg_365[11:0] <= 12'b100000000000;
    thr_add1_reg_370[11:0] <= 12'b100000000000;
    thr_add3_reg_375[11:0] <= 12'b100000000000;
end

endmodule //bd_19ea_csc_0_v_csc_core
