// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_19ea_csc_0_v_csc_core_Pipeline_VITIS_LOOP_136_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_in_dout,
        stream_in_num_data_valid,
        stream_in_fifo_cap,
        stream_in_empty_n,
        stream_in_read,
        stream_csc_din,
        stream_csc_num_data_valid,
        stream_csc_fifo_cap,
        stream_csc_full_n,
        stream_csc_write,
        add_ln134,
        K12_load_cast,
        K13_load_cast,
        K11_load_cast,
        thr_add131_cast,
        K22_load_cast,
        K23_load_cast,
        K21_load_cast,
        thr_add62_cast,
        K32_load_cast,
        K33_load_cast,
        K31_load_cast,
        sext_ln134,
        p_read12_cast,
        p_read13_cast,
        ClipMax_read,
        ClampMin_read
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] stream_in_dout;
input  [4:0] stream_in_num_data_valid;
input  [4:0] stream_in_fifo_cap;
input   stream_in_empty_n;
output   stream_in_read;
output  [23:0] stream_csc_din;
input  [4:0] stream_csc_num_data_valid;
input  [4:0] stream_csc_fifo_cap;
input   stream_csc_full_n;
output   stream_csc_write;
input  [11:0] add_ln134;
input  [15:0] K12_load_cast;
input  [15:0] K13_load_cast;
input  [15:0] K11_load_cast;
input  [21:0] thr_add131_cast;
input  [15:0] K22_load_cast;
input  [15:0] K23_load_cast;
input  [15:0] K21_load_cast;
input  [21:0] thr_add62_cast;
input  [15:0] K32_load_cast;
input  [15:0] K33_load_cast;
input  [15:0] K31_load_cast;
input  [21:0] sext_ln134;
input  [7:0] p_read12_cast;
input  [7:0] p_read13_cast;
input  [7:0] ClipMax_read;
input  [7:0] ClampMin_read;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln136_fu_281_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    stream_in_blk_n;
wire    ap_block_pp0_stage0;
reg    stream_csc_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [13:0] p_read13_cast_cast_fu_217_p1;
reg   [13:0] p_read13_cast_cast_reg_661;
wire   [13:0] p_read12_cast_cast_fu_221_p1;
reg   [13:0] p_read12_cast_cast_reg_668;
wire  signed [24:0] sext_ln134_cast_fu_225_p1;
reg  signed [24:0] sext_ln134_cast_reg_675;
wire  signed [23:0] K31_load_cast_cast_fu_229_p1;
reg  signed [23:0] K31_load_cast_cast_reg_680;
wire  signed [23:0] K33_load_cast_cast_fu_233_p1;
reg  signed [23:0] K33_load_cast_cast_reg_685;
wire  signed [23:0] K32_load_cast_cast_fu_237_p1;
reg  signed [23:0] K32_load_cast_cast_reg_690;
wire  signed [24:0] thr_add62_cast_cast_fu_241_p1;
reg  signed [24:0] thr_add62_cast_cast_reg_695;
wire  signed [23:0] K21_load_cast_cast_fu_245_p1;
reg  signed [23:0] K21_load_cast_cast_reg_700;
wire  signed [23:0] K23_load_cast_cast_fu_249_p1;
reg  signed [23:0] K23_load_cast_cast_reg_705;
wire  signed [23:0] K22_load_cast_cast_fu_253_p1;
reg  signed [23:0] K22_load_cast_cast_reg_710;
wire  signed [24:0] thr_add131_cast_cast_fu_257_p1;
reg  signed [24:0] thr_add131_cast_cast_reg_715;
wire  signed [23:0] K11_load_cast_cast_fu_261_p1;
reg  signed [23:0] K11_load_cast_cast_reg_720;
wire  signed [23:0] K13_load_cast_cast_fu_265_p1;
reg  signed [23:0] K13_load_cast_cast_reg_725;
wire  signed [23:0] K12_load_cast_cast_fu_269_p1;
reg  signed [23:0] K12_load_cast_cast_reg_730;
wire   [7:0] Rpix_fu_298_p1;
reg   [7:0] Rpix_reg_739;
reg   [7:0] Bpix_reg_744;
wire   [23:0] zext_ln106_1_fu_322_p1;
wire   [23:0] zext_ln140_fu_326_p1;
wire   [23:0] zext_ln106_fu_329_p1;
wire  signed [23:0] grp_fu_332_p2;
reg  signed [23:0] mul_ln192_1_reg_770;
wire  signed [23:0] grp_fu_337_p2;
reg  signed [23:0] mul_ln192_2_reg_776;
wire  signed [23:0] grp_fu_342_p2;
reg  signed [23:0] mul_ln194_1_reg_782;
wire  signed [23:0] grp_fu_347_p2;
reg  signed [23:0] mul_ln194_2_reg_788;
wire  signed [23:0] grp_fu_352_p2;
reg  signed [23:0] mul_ln196_1_reg_794;
wire  signed [23:0] grp_fu_357_p2;
reg  signed [23:0] mul_ln196_2_reg_800;
wire   [19:0] trunc_ln192_fu_368_p1;
reg   [19:0] trunc_ln192_reg_806;
wire   [19:0] trunc_ln192_1_fu_384_p1;
reg   [19:0] trunc_ln192_1_reg_811;
reg   [13:0] Rres_reg_816;
wire   [19:0] trunc_ln194_fu_414_p1;
reg   [19:0] trunc_ln194_reg_822;
wire   [19:0] trunc_ln194_1_fu_430_p1;
reg   [19:0] trunc_ln194_1_reg_827;
reg   [13:0] Gres_reg_832;
wire   [19:0] trunc_ln196_fu_460_p1;
reg   [19:0] trunc_ln196_reg_838;
wire   [19:0] trunc_ln196_1_fu_476_p1;
reg   [19:0] trunc_ln196_1_reg_843;
reg   [13:0] Bres_reg_848;
wire   [7:0] select_ln198_1_fu_537_p3;
reg   [7:0] select_ln198_1_reg_854;
wire   [7:0] select_ln200_1_fu_587_p3;
reg   [7:0] select_ln200_1_reg_859;
wire   [7:0] select_ln199_1_fu_601_p3;
reg   [7:0] select_ln199_1_reg_864;
reg   [11:0] x_fu_98;
wire   [11:0] x_3_fu_287_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_x_2;
reg    stream_in_read_local;
wire   [23:0] or_ln205_3_fu_608_p4;
reg    ap_block_pp0_stage0_01001;
reg    stream_csc_write_local;
wire   [7:0] Gpix_fu_302_p4;
wire   [7:0] grp_fu_332_p0;
wire  signed [15:0] grp_fu_332_p1;
wire  signed [15:0] grp_fu_337_p0;
wire   [7:0] grp_fu_337_p1;
wire   [7:0] grp_fu_342_p0;
wire  signed [15:0] grp_fu_342_p1;
wire  signed [15:0] grp_fu_347_p0;
wire   [7:0] grp_fu_347_p1;
wire   [7:0] grp_fu_352_p0;
wire  signed [15:0] grp_fu_352_p1;
wire  signed [15:0] grp_fu_357_p0;
wire   [7:0] grp_fu_357_p1;
wire  signed [24:0] grp_fu_616_p3;
wire  signed [24:0] sext_ln192_2_fu_365_p1;
wire  signed [24:0] sext_ln192_1_fu_362_p1;
wire   [23:0] add_ln192_4_fu_374_p2;
wire   [24:0] add_ln192_1_fu_378_p2;
wire  signed [25:0] sext_ln192_4_fu_388_p1;
wire  signed [25:0] sext_ln192_3_fu_371_p1;
wire   [25:0] add_ln192_2_fu_392_p2;
wire  signed [24:0] grp_fu_624_p3;
wire  signed [24:0] sext_ln194_2_fu_411_p1;
wire  signed [24:0] sext_ln194_1_fu_408_p1;
wire   [23:0] add_ln194_4_fu_420_p2;
wire   [24:0] add_ln194_1_fu_424_p2;
wire  signed [25:0] sext_ln194_4_fu_434_p1;
wire  signed [25:0] sext_ln194_3_fu_417_p1;
wire   [25:0] add_ln194_2_fu_438_p2;
wire  signed [24:0] grp_fu_632_p3;
wire  signed [24:0] sext_ln196_2_fu_457_p1;
wire  signed [24:0] sext_ln196_1_fu_454_p1;
wire   [23:0] add_ln196_4_fu_466_p2;
wire   [24:0] add_ln196_1_fu_470_p2;
wire  signed [25:0] sext_ln196_4_fu_480_p1;
wire  signed [25:0] sext_ln196_3_fu_463_p1;
wire   [25:0] add_ln196_2_fu_484_p2;
wire   [19:0] add_ln192_3_fu_500_p2;
wire   [0:0] icmp_ln198_1_fu_516_p2;
wire   [7:0] trunc_ln_fu_520_p4;
wire   [0:0] icmp_ln198_fu_512_p2;
wire   [7:0] select_ln198_fu_530_p3;
wire   [19:0] add_ln194_3_fu_504_p2;
wire   [19:0] add_ln196_3_fu_508_p2;
wire   [0:0] icmp_ln200_1_fu_566_p2;
wire   [7:0] trunc_ln2_fu_570_p4;
wire   [0:0] icmp_ln200_fu_562_p2;
wire   [7:0] select_ln200_fu_580_p3;
wire   [0:0] icmp_ln199_1_fu_548_p2;
wire   [7:0] trunc_ln1_fu_552_p4;
wire   [0:0] icmp_ln199_fu_544_p2;
wire   [7:0] select_ln199_fu_594_p3;
wire  signed [15:0] grp_fu_616_p0;
wire   [7:0] grp_fu_616_p1;
wire  signed [21:0] grp_fu_616_p2;
wire  signed [15:0] grp_fu_624_p0;
wire   [7:0] grp_fu_624_p1;
wire  signed [21:0] grp_fu_624_p2;
wire  signed [15:0] grp_fu_632_p0;
wire   [7:0] grp_fu_632_p1;
wire  signed [21:0] grp_fu_632_p2;
reg    grp_fu_332_ce;
reg    grp_fu_337_ce;
reg    grp_fu_342_ce;
reg    grp_fu_347_ce;
reg    grp_fu_352_ce;
reg    grp_fu_357_ce;
reg    grp_fu_616_ce;
reg    grp_fu_624_ce;
reg    grp_fu_632_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 x_fu_98 = 12'd0;
#0 ap_done_reg = 1'b0;
end

bd_19ea_csc_0_mul_8ns_16s_24_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_2_1_U74(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_332_p0),
    .din1(grp_fu_332_p1),
    .ce(grp_fu_332_ce),
    .dout(grp_fu_332_p2)
);

bd_19ea_csc_0_mul_16s_8ns_24_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_2_1_U75(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_337_p0),
    .din1(grp_fu_337_p1),
    .ce(grp_fu_337_ce),
    .dout(grp_fu_337_p2)
);

bd_19ea_csc_0_mul_8ns_16s_24_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_2_1_U76(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_342_p0),
    .din1(grp_fu_342_p1),
    .ce(grp_fu_342_ce),
    .dout(grp_fu_342_p2)
);

bd_19ea_csc_0_mul_16s_8ns_24_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_2_1_U77(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_347_p0),
    .din1(grp_fu_347_p1),
    .ce(grp_fu_347_ce),
    .dout(grp_fu_347_p2)
);

bd_19ea_csc_0_mul_8ns_16s_24_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_2_1_U78(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_352_p0),
    .din1(grp_fu_352_p1),
    .ce(grp_fu_352_ce),
    .dout(grp_fu_352_p2)
);

bd_19ea_csc_0_mul_16s_8ns_24_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_2_1_U79(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_357_p0),
    .din1(grp_fu_357_p1),
    .ce(grp_fu_357_ce),
    .dout(grp_fu_357_p2)
);

bd_19ea_csc_0_mac_muladd_16s_8ns_22s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8ns_22s_25_4_1_U80(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_616_p0),
    .din1(grp_fu_616_p1),
    .din2(grp_fu_616_p2),
    .ce(grp_fu_616_ce),
    .dout(grp_fu_616_p3)
);

bd_19ea_csc_0_mac_muladd_16s_8ns_22s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8ns_22s_25_4_1_U81(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_624_p0),
    .din1(grp_fu_624_p1),
    .din2(grp_fu_624_p2),
    .ce(grp_fu_624_ce),
    .dout(grp_fu_624_p3)
);

bd_19ea_csc_0_mac_muladd_16s_8ns_22s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8ns_22s_25_4_1_U82(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_632_p0),
    .din1(grp_fu_632_p1),
    .din2(grp_fu_632_p2),
    .ce(grp_fu_632_ce),
    .dout(grp_fu_632_p3)
);

bd_19ea_csc_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln136_fu_281_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_98 <= x_3_fu_287_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_98 <= 12'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Bpix_reg_744 <= {{stream_in_dout[23:16]}};
        K11_load_cast_cast_reg_720 <= K11_load_cast_cast_fu_261_p1;
        K12_load_cast_cast_reg_730 <= K12_load_cast_cast_fu_269_p1;
        K13_load_cast_cast_reg_725 <= K13_load_cast_cast_fu_265_p1;
        K21_load_cast_cast_reg_700 <= K21_load_cast_cast_fu_245_p1;
        K22_load_cast_cast_reg_710 <= K22_load_cast_cast_fu_253_p1;
        K23_load_cast_cast_reg_705 <= K23_load_cast_cast_fu_249_p1;
        K31_load_cast_cast_reg_680 <= K31_load_cast_cast_fu_229_p1;
        K32_load_cast_cast_reg_690 <= K32_load_cast_cast_fu_237_p1;
        K33_load_cast_cast_reg_685 <= K33_load_cast_cast_fu_233_p1;
        Rpix_reg_739 <= Rpix_fu_298_p1;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        p_read12_cast_cast_reg_668[7 : 0] <= p_read12_cast_cast_fu_221_p1[7 : 0];
        p_read13_cast_cast_reg_661[7 : 0] <= p_read13_cast_cast_fu_217_p1[7 : 0];
        sext_ln134_cast_reg_675 <= sext_ln134_cast_fu_225_p1;
        thr_add131_cast_cast_reg_715 <= thr_add131_cast_cast_fu_257_p1;
        thr_add62_cast_cast_reg_695 <= thr_add62_cast_cast_fu_241_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Bres_reg_848 <= {{add_ln196_2_fu_484_p2[25:12]}};
        Gres_reg_832 <= {{add_ln194_2_fu_438_p2[25:12]}};
        Rres_reg_816 <= {{add_ln192_2_fu_392_p2[25:12]}};
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        mul_ln192_1_reg_770 <= grp_fu_332_p2;
        mul_ln192_2_reg_776 <= grp_fu_337_p2;
        mul_ln194_1_reg_782 <= grp_fu_342_p2;
        mul_ln194_2_reg_788 <= grp_fu_347_p2;
        mul_ln196_1_reg_794 <= grp_fu_352_p2;
        mul_ln196_2_reg_800 <= grp_fu_357_p2;
        select_ln198_1_reg_854 <= select_ln198_1_fu_537_p3;
        select_ln199_1_reg_864 <= select_ln199_1_fu_601_p3;
        select_ln200_1_reg_859 <= select_ln200_1_fu_587_p3;
        trunc_ln192_1_reg_811 <= trunc_ln192_1_fu_384_p1;
        trunc_ln192_reg_806 <= trunc_ln192_fu_368_p1;
        trunc_ln194_1_reg_827 <= trunc_ln194_1_fu_430_p1;
        trunc_ln194_reg_822 <= trunc_ln194_fu_414_p1;
        trunc_ln196_1_reg_843 <= trunc_ln196_1_fu_476_p1;
        trunc_ln196_reg_838 <= trunc_ln196_fu_460_p1;
    end
end

always @ (*) begin
    if (((icmp_ln136_fu_281_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_2 = 12'd1;
    end else begin
        ap_sig_allocacmp_x_2 = x_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_332_ce = 1'b1;
    end else begin
        grp_fu_332_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_337_ce = 1'b1;
    end else begin
        grp_fu_337_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_342_ce = 1'b1;
    end else begin
        grp_fu_342_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_347_ce = 1'b1;
    end else begin
        grp_fu_347_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_352_ce = 1'b1;
    end else begin
        grp_fu_352_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_357_ce = 1'b1;
    end else begin
        grp_fu_357_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_616_ce = 1'b1;
    end else begin
        grp_fu_616_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_624_ce = 1'b1;
    end else begin
        grp_fu_624_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_632_ce = 1'b1;
    end else begin
        grp_fu_632_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        stream_csc_blk_n = stream_csc_full_n;
    end else begin
        stream_csc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        stream_csc_write_local = 1'b1;
    end else begin
        stream_csc_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_blk_n = stream_in_empty_n;
    end else begin
        stream_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_read_local = 1'b1;
    end else begin
        stream_in_read_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Gpix_fu_302_p4 = {{stream_in_dout[15:8]}};

assign K11_load_cast_cast_fu_261_p1 = $signed(K11_load_cast);

assign K12_load_cast_cast_fu_269_p1 = $signed(K12_load_cast);

assign K13_load_cast_cast_fu_265_p1 = $signed(K13_load_cast);

assign K21_load_cast_cast_fu_245_p1 = $signed(K21_load_cast);

assign K22_load_cast_cast_fu_253_p1 = $signed(K22_load_cast);

assign K23_load_cast_cast_fu_249_p1 = $signed(K23_load_cast);

assign K31_load_cast_cast_fu_229_p1 = $signed(K31_load_cast);

assign K32_load_cast_cast_fu_237_p1 = $signed(K32_load_cast);

assign K33_load_cast_cast_fu_233_p1 = $signed(K33_load_cast);

assign Rpix_fu_298_p1 = stream_in_dout[7:0];

assign add_ln192_1_fu_378_p2 = ($signed(sext_ln192_2_fu_365_p1) + $signed(sext_ln192_1_fu_362_p1));

assign add_ln192_2_fu_392_p2 = ($signed(sext_ln192_4_fu_388_p1) + $signed(sext_ln192_3_fu_371_p1));

assign add_ln192_3_fu_500_p2 = (trunc_ln192_1_reg_811 + trunc_ln192_reg_806);

assign add_ln192_4_fu_374_p2 = ($signed(mul_ln192_2_reg_776) + $signed(mul_ln192_1_reg_770));

assign add_ln194_1_fu_424_p2 = ($signed(sext_ln194_2_fu_411_p1) + $signed(sext_ln194_1_fu_408_p1));

assign add_ln194_2_fu_438_p2 = ($signed(sext_ln194_4_fu_434_p1) + $signed(sext_ln194_3_fu_417_p1));

assign add_ln194_3_fu_504_p2 = (trunc_ln194_1_reg_827 + trunc_ln194_reg_822);

assign add_ln194_4_fu_420_p2 = ($signed(mul_ln194_2_reg_788) + $signed(mul_ln194_1_reg_782));

assign add_ln196_1_fu_470_p2 = ($signed(sext_ln196_2_fu_457_p1) + $signed(sext_ln196_1_fu_454_p1));

assign add_ln196_2_fu_484_p2 = ($signed(sext_ln196_4_fu_480_p1) + $signed(sext_ln196_3_fu_463_p1));

assign add_ln196_3_fu_508_p2 = (trunc_ln196_1_reg_843 + trunc_ln196_reg_838);

assign add_ln196_4_fu_466_p2 = ($signed(mul_ln196_2_reg_800) + $signed(mul_ln196_1_reg_794));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (stream_in_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6 = (stream_csc_full_n == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_332_p0 = zext_ln140_fu_326_p1;

assign grp_fu_332_p1 = K13_load_cast_cast_reg_725;

assign grp_fu_337_p0 = K11_load_cast_cast_reg_720;

assign grp_fu_337_p1 = zext_ln106_fu_329_p1;

assign grp_fu_342_p0 = zext_ln140_fu_326_p1;

assign grp_fu_342_p1 = K23_load_cast_cast_reg_705;

assign grp_fu_347_p0 = K21_load_cast_cast_reg_700;

assign grp_fu_347_p1 = zext_ln106_fu_329_p1;

assign grp_fu_352_p0 = zext_ln140_fu_326_p1;

assign grp_fu_352_p1 = K33_load_cast_cast_reg_685;

assign grp_fu_357_p0 = K31_load_cast_cast_reg_680;

assign grp_fu_357_p1 = zext_ln106_fu_329_p1;

assign grp_fu_616_p0 = K12_load_cast_cast_reg_730;

assign grp_fu_616_p1 = zext_ln106_1_fu_322_p1;

assign grp_fu_616_p2 = thr_add131_cast_cast_reg_715;

assign grp_fu_624_p0 = K22_load_cast_cast_reg_710;

assign grp_fu_624_p1 = zext_ln106_1_fu_322_p1;

assign grp_fu_624_p2 = thr_add62_cast_cast_reg_695;

assign grp_fu_632_p0 = K32_load_cast_cast_reg_690;

assign grp_fu_632_p1 = zext_ln106_1_fu_322_p1;

assign grp_fu_632_p2 = sext_ln134_cast_reg_675;

assign icmp_ln136_fu_281_p2 = ((ap_sig_allocacmp_x_2 == add_ln134) ? 1'b1 : 1'b0);

assign icmp_ln198_1_fu_516_p2 = (($signed(Rres_reg_816) > $signed(p_read13_cast_cast_reg_661)) ? 1'b1 : 1'b0);

assign icmp_ln198_fu_512_p2 = (($signed(Rres_reg_816) < $signed(p_read12_cast_cast_reg_668)) ? 1'b1 : 1'b0);

assign icmp_ln199_1_fu_548_p2 = (($signed(Gres_reg_832) > $signed(p_read13_cast_cast_reg_661)) ? 1'b1 : 1'b0);

assign icmp_ln199_fu_544_p2 = (($signed(Gres_reg_832) < $signed(p_read12_cast_cast_reg_668)) ? 1'b1 : 1'b0);

assign icmp_ln200_1_fu_566_p2 = (($signed(Bres_reg_848) > $signed(p_read13_cast_cast_reg_661)) ? 1'b1 : 1'b0);

assign icmp_ln200_fu_562_p2 = (($signed(Bres_reg_848) < $signed(p_read12_cast_cast_reg_668)) ? 1'b1 : 1'b0);

assign or_ln205_3_fu_608_p4 = {{{select_ln200_1_reg_859}, {select_ln199_1_reg_864}}, {select_ln198_1_reg_854}};

assign p_read12_cast_cast_fu_221_p1 = p_read12_cast;

assign p_read13_cast_cast_fu_217_p1 = p_read13_cast;

assign select_ln198_1_fu_537_p3 = ((icmp_ln198_fu_512_p2[0:0] == 1'b1) ? ClampMin_read : select_ln198_fu_530_p3);

assign select_ln198_fu_530_p3 = ((icmp_ln198_1_fu_516_p2[0:0] == 1'b1) ? ClipMax_read : trunc_ln_fu_520_p4);

assign select_ln199_1_fu_601_p3 = ((icmp_ln199_fu_544_p2[0:0] == 1'b1) ? ClampMin_read : select_ln199_fu_594_p3);

assign select_ln199_fu_594_p3 = ((icmp_ln199_1_fu_548_p2[0:0] == 1'b1) ? ClipMax_read : trunc_ln1_fu_552_p4);

assign select_ln200_1_fu_587_p3 = ((icmp_ln200_fu_562_p2[0:0] == 1'b1) ? ClampMin_read : select_ln200_fu_580_p3);

assign select_ln200_fu_580_p3 = ((icmp_ln200_1_fu_566_p2[0:0] == 1'b1) ? ClipMax_read : trunc_ln2_fu_570_p4);

assign sext_ln134_cast_fu_225_p1 = $signed(sext_ln134);

assign sext_ln192_1_fu_362_p1 = mul_ln192_1_reg_770;

assign sext_ln192_2_fu_365_p1 = mul_ln192_2_reg_776;

assign sext_ln192_3_fu_371_p1 = grp_fu_616_p3;

assign sext_ln192_4_fu_388_p1 = $signed(add_ln192_1_fu_378_p2);

assign sext_ln194_1_fu_408_p1 = mul_ln194_1_reg_782;

assign sext_ln194_2_fu_411_p1 = mul_ln194_2_reg_788;

assign sext_ln194_3_fu_417_p1 = grp_fu_624_p3;

assign sext_ln194_4_fu_434_p1 = $signed(add_ln194_1_fu_424_p2);

assign sext_ln196_1_fu_454_p1 = mul_ln196_1_reg_794;

assign sext_ln196_2_fu_457_p1 = mul_ln196_2_reg_800;

assign sext_ln196_3_fu_463_p1 = grp_fu_632_p3;

assign sext_ln196_4_fu_480_p1 = $signed(add_ln196_1_fu_470_p2);

assign stream_csc_din = or_ln205_3_fu_608_p4;

assign stream_csc_write = stream_csc_write_local;

assign stream_in_read = stream_in_read_local;

assign thr_add131_cast_cast_fu_257_p1 = $signed(thr_add131_cast);

assign thr_add62_cast_cast_fu_241_p1 = $signed(thr_add62_cast);

assign trunc_ln192_1_fu_384_p1 = add_ln192_4_fu_374_p2[19:0];

assign trunc_ln192_fu_368_p1 = grp_fu_616_p3[19:0];

assign trunc_ln194_1_fu_430_p1 = add_ln194_4_fu_420_p2[19:0];

assign trunc_ln194_fu_414_p1 = grp_fu_624_p3[19:0];

assign trunc_ln196_1_fu_476_p1 = add_ln196_4_fu_466_p2[19:0];

assign trunc_ln196_fu_460_p1 = grp_fu_632_p3[19:0];

assign trunc_ln1_fu_552_p4 = {{add_ln194_3_fu_504_p2[19:12]}};

assign trunc_ln2_fu_570_p4 = {{add_ln196_3_fu_508_p2[19:12]}};

assign trunc_ln_fu_520_p4 = {{add_ln192_3_fu_500_p2[19:12]}};

assign x_3_fu_287_p2 = (ap_sig_allocacmp_x_2 + 12'd1);

assign zext_ln106_1_fu_322_p1 = Gpix_fu_302_p4;

assign zext_ln106_fu_329_p1 = Rpix_reg_739;

assign zext_ln140_fu_326_p1 = Bpix_reg_744;

always @ (posedge ap_clk) begin
    p_read13_cast_cast_reg_661[13:8] <= 6'b000000;
    p_read12_cast_cast_reg_668[13:8] <= 6'b000000;
end

endmodule //bd_19ea_csc_0_v_csc_core_Pipeline_VITIS_LOOP_136_2
