// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="bd_19ea_csc_0_v_csc,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=6.734000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.302000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4472,HLS_SYN_LUT=4055,HLS_VERSION=2024_1}" *)

module bd_19ea_csc_0_v_csc (
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        s_axis_video_TDATA,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        m_axis_video_TDATA,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        m_axis_video_TVALID,
        m_axis_video_TREADY
);

parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [23:0] s_axis_video_TDATA;
input  [2:0] s_axis_video_TKEEP;
input  [2:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [23:0] m_axis_video_TDATA;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;

 reg    ap_rst_n_inv;
wire   [7:0] InVideoFormat;
wire   [7:0] OutVideoFormat;
wire   [15:0] width;
wire   [15:0] height;
wire   [15:0] K11;
wire   [15:0] K12;
wire   [15:0] K13;
wire   [15:0] K21;
wire   [15:0] K22;
wire   [15:0] K23;
wire   [15:0] K31;
wire   [15:0] K32;
wire   [15:0] K33;
wire   [9:0] ROffset;
wire   [9:0] GOffset;
wire   [9:0] BOffset;
wire   [7:0] ClampMin;
wire   [7:0] ClipMax;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    Block_entry_split_proc_U0_ap_start;
wire    Block_entry_split_proc_U0_ap_done;
wire    Block_entry_split_proc_U0_ap_continue;
wire    Block_entry_split_proc_U0_ap_idle;
wire    Block_entry_split_proc_U0_ap_ready;
wire   [7:0] Block_entry_split_proc_U0_ap_return_0;
wire   [7:0] Block_entry_split_proc_U0_ap_return_1;
wire   [15:0] Block_entry_split_proc_U0_ap_return_2;
wire   [15:0] Block_entry_split_proc_U0_ap_return_3;
wire   [15:0] Block_entry_split_proc_U0_ap_return_4;
wire   [15:0] Block_entry_split_proc_U0_ap_return_5;
wire   [15:0] Block_entry_split_proc_U0_ap_return_6;
wire   [15:0] Block_entry_split_proc_U0_ap_return_7;
wire   [15:0] Block_entry_split_proc_U0_ap_return_8;
wire   [15:0] Block_entry_split_proc_U0_ap_return_9;
wire   [15:0] Block_entry_split_proc_U0_ap_return_10;
wire   [9:0] Block_entry_split_proc_U0_ap_return_11;
wire   [9:0] Block_entry_split_proc_U0_ap_return_12;
wire   [9:0] Block_entry_split_proc_U0_ap_return_13;
wire   [7:0] Block_entry_split_proc_U0_ap_return_14;
wire   [7:0] Block_entry_split_proc_U0_ap_return_15;
wire   [10:0] Block_entry_split_proc_U0_ap_return_16;
wire   [10:0] Block_entry_split_proc_U0_ap_return_17;
wire    ap_channel_done_HwReg_height_c6_channel;
wire    HwReg_height_c6_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_height_c6_channel;
wire    ap_sync_channel_write_HwReg_height_c6_channel;
wire    ap_channel_done_HwReg_width_c4_channel;
wire    HwReg_width_c4_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_width_c4_channel;
wire    ap_sync_channel_write_HwReg_width_c4_channel;
wire    ap_channel_done_HwReg_ClipMax_channel;
wire    HwReg_ClipMax_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_ClipMax_channel;
wire    ap_sync_channel_write_HwReg_ClipMax_channel;
wire    ap_channel_done_HwReg_ClampMin_channel;
wire    HwReg_ClampMin_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_ClampMin_channel;
wire    ap_sync_channel_write_HwReg_ClampMin_channel;
wire    ap_channel_done_HwReg_BOffset_channel;
wire    HwReg_BOffset_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_BOffset_channel;
wire    ap_sync_channel_write_HwReg_BOffset_channel;
wire    ap_channel_done_HwReg_GOffset_channel;
wire    HwReg_GOffset_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_GOffset_channel;
wire    ap_sync_channel_write_HwReg_GOffset_channel;
wire    ap_channel_done_HwReg_ROffset_channel;
wire    HwReg_ROffset_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_ROffset_channel;
wire    ap_sync_channel_write_HwReg_ROffset_channel;
wire    ap_channel_done_HwReg_K33_channel;
wire    HwReg_K33_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_K33_channel;
wire    ap_sync_channel_write_HwReg_K33_channel;
wire    ap_channel_done_HwReg_K32_channel;
wire    HwReg_K32_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_K32_channel;
wire    ap_sync_channel_write_HwReg_K32_channel;
wire    ap_channel_done_HwReg_K31_channel;
wire    HwReg_K31_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_K31_channel;
wire    ap_sync_channel_write_HwReg_K31_channel;
wire    ap_channel_done_HwReg_K23_channel;
wire    HwReg_K23_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_K23_channel;
wire    ap_sync_channel_write_HwReg_K23_channel;
wire    ap_channel_done_HwReg_K22_channel;
wire    HwReg_K22_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_K22_channel;
wire    ap_sync_channel_write_HwReg_K22_channel;
wire    ap_channel_done_HwReg_K21_channel;
wire    HwReg_K21_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_K21_channel;
wire    ap_sync_channel_write_HwReg_K21_channel;
wire    ap_channel_done_HwReg_K13_channel;
wire    HwReg_K13_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_K13_channel;
wire    ap_sync_channel_write_HwReg_K13_channel;
wire    ap_channel_done_HwReg_K12_channel;
wire    HwReg_K12_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_K12_channel;
wire    ap_sync_channel_write_HwReg_K12_channel;
wire    ap_channel_done_HwReg_K11_channel;
wire    HwReg_K11_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_K11_channel;
wire    ap_sync_channel_write_HwReg_K11_channel;
wire    ap_channel_done_HwReg_OutVideoFormat_channel;
wire    HwReg_OutVideoFormat_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_OutVideoFormat_channel;
wire    ap_sync_channel_write_HwReg_OutVideoFormat_channel;
wire    ap_channel_done_HwReg_InVideoFormat_channel;
wire    HwReg_InVideoFormat_channel_full_n;
reg    ap_sync_reg_channel_write_HwReg_InVideoFormat_channel;
wire    ap_sync_channel_write_HwReg_InVideoFormat_channel;
wire    AXIvideo2MultiPixStream_U0_ap_start;
wire    AXIvideo2MultiPixStream_U0_ap_done;
wire    AXIvideo2MultiPixStream_U0_ap_continue;
wire    AXIvideo2MultiPixStream_U0_ap_idle;
wire    AXIvideo2MultiPixStream_U0_ap_ready;
wire    AXIvideo2MultiPixStream_U0_s_axis_video_TREADY;
wire   [23:0] AXIvideo2MultiPixStream_U0_stream_in_din;
wire    AXIvideo2MultiPixStream_U0_stream_in_write;
wire   [10:0] AXIvideo2MultiPixStream_U0_HwReg_width_c3_din;
wire    AXIvideo2MultiPixStream_U0_HwReg_width_c3_write;
wire   [10:0] AXIvideo2MultiPixStream_U0_HwReg_height_c5_din;
wire    AXIvideo2MultiPixStream_U0_HwReg_height_c5_write;
wire    v_csc_core_U0_ap_start;
wire    v_csc_core_U0_ap_done;
wire    v_csc_core_U0_ap_continue;
wire    v_csc_core_U0_ap_idle;
wire    v_csc_core_U0_ap_ready;
wire    v_csc_core_U0_stream_in_read;
wire    v_csc_core_U0_height_read;
wire    v_csc_core_U0_width_read;
wire   [23:0] v_csc_core_U0_stream_csc_din;
wire    v_csc_core_U0_stream_csc_write;
wire   [10:0] v_csc_core_U0_HwReg_width_c_din;
wire    v_csc_core_U0_HwReg_width_c_write;
wire   [10:0] v_csc_core_U0_HwReg_height_c_din;
wire    v_csc_core_U0_HwReg_height_c_write;
wire    MultiPixStream2AXIvideo_U0_ap_start;
wire    MultiPixStream2AXIvideo_U0_ap_done;
wire    MultiPixStream2AXIvideo_U0_ap_continue;
wire    MultiPixStream2AXIvideo_U0_ap_idle;
wire    MultiPixStream2AXIvideo_U0_ap_ready;
wire    MultiPixStream2AXIvideo_U0_stream_csc_read;
wire   [23:0] MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;
wire    MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;
wire   [2:0] MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;
wire   [2:0] MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TID;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;
wire    MultiPixStream2AXIvideo_U0_Height_read;
wire    MultiPixStream2AXIvideo_U0_WidthOut_read;
wire   [7:0] HwReg_InVideoFormat_channel_dout;
wire   [2:0] HwReg_InVideoFormat_channel_num_data_valid;
wire   [2:0] HwReg_InVideoFormat_channel_fifo_cap;
wire    HwReg_InVideoFormat_channel_empty_n;
wire   [7:0] HwReg_OutVideoFormat_channel_dout;
wire   [2:0] HwReg_OutVideoFormat_channel_num_data_valid;
wire   [2:0] HwReg_OutVideoFormat_channel_fifo_cap;
wire    HwReg_OutVideoFormat_channel_empty_n;
wire   [15:0] HwReg_K11_channel_dout;
wire   [2:0] HwReg_K11_channel_num_data_valid;
wire   [2:0] HwReg_K11_channel_fifo_cap;
wire    HwReg_K11_channel_empty_n;
wire   [15:0] HwReg_K12_channel_dout;
wire   [2:0] HwReg_K12_channel_num_data_valid;
wire   [2:0] HwReg_K12_channel_fifo_cap;
wire    HwReg_K12_channel_empty_n;
wire   [15:0] HwReg_K13_channel_dout;
wire   [2:0] HwReg_K13_channel_num_data_valid;
wire   [2:0] HwReg_K13_channel_fifo_cap;
wire    HwReg_K13_channel_empty_n;
wire   [15:0] HwReg_K21_channel_dout;
wire   [2:0] HwReg_K21_channel_num_data_valid;
wire   [2:0] HwReg_K21_channel_fifo_cap;
wire    HwReg_K21_channel_empty_n;
wire   [15:0] HwReg_K22_channel_dout;
wire   [2:0] HwReg_K22_channel_num_data_valid;
wire   [2:0] HwReg_K22_channel_fifo_cap;
wire    HwReg_K22_channel_empty_n;
wire   [15:0] HwReg_K23_channel_dout;
wire   [2:0] HwReg_K23_channel_num_data_valid;
wire   [2:0] HwReg_K23_channel_fifo_cap;
wire    HwReg_K23_channel_empty_n;
wire   [15:0] HwReg_K31_channel_dout;
wire   [2:0] HwReg_K31_channel_num_data_valid;
wire   [2:0] HwReg_K31_channel_fifo_cap;
wire    HwReg_K31_channel_empty_n;
wire   [15:0] HwReg_K32_channel_dout;
wire   [2:0] HwReg_K32_channel_num_data_valid;
wire   [2:0] HwReg_K32_channel_fifo_cap;
wire    HwReg_K32_channel_empty_n;
wire   [15:0] HwReg_K33_channel_dout;
wire   [2:0] HwReg_K33_channel_num_data_valid;
wire   [2:0] HwReg_K33_channel_fifo_cap;
wire    HwReg_K33_channel_empty_n;
wire   [9:0] HwReg_ROffset_channel_dout;
wire   [2:0] HwReg_ROffset_channel_num_data_valid;
wire   [2:0] HwReg_ROffset_channel_fifo_cap;
wire    HwReg_ROffset_channel_empty_n;
wire   [9:0] HwReg_GOffset_channel_dout;
wire   [2:0] HwReg_GOffset_channel_num_data_valid;
wire   [2:0] HwReg_GOffset_channel_fifo_cap;
wire    HwReg_GOffset_channel_empty_n;
wire   [9:0] HwReg_BOffset_channel_dout;
wire   [2:0] HwReg_BOffset_channel_num_data_valid;
wire   [2:0] HwReg_BOffset_channel_fifo_cap;
wire    HwReg_BOffset_channel_empty_n;
wire   [7:0] HwReg_ClampMin_channel_dout;
wire   [2:0] HwReg_ClampMin_channel_num_data_valid;
wire   [2:0] HwReg_ClampMin_channel_fifo_cap;
wire    HwReg_ClampMin_channel_empty_n;
wire   [7:0] HwReg_ClipMax_channel_dout;
wire   [2:0] HwReg_ClipMax_channel_num_data_valid;
wire   [2:0] HwReg_ClipMax_channel_fifo_cap;
wire    HwReg_ClipMax_channel_empty_n;
wire   [10:0] HwReg_width_c4_channel_dout;
wire   [2:0] HwReg_width_c4_channel_num_data_valid;
wire   [2:0] HwReg_width_c4_channel_fifo_cap;
wire    HwReg_width_c4_channel_empty_n;
wire   [10:0] HwReg_height_c6_channel_dout;
wire   [2:0] HwReg_height_c6_channel_num_data_valid;
wire   [2:0] HwReg_height_c6_channel_fifo_cap;
wire    HwReg_height_c6_channel_empty_n;
wire    stream_in_full_n;
wire   [23:0] stream_in_dout;
wire   [4:0] stream_in_num_data_valid;
wire   [4:0] stream_in_fifo_cap;
wire    stream_in_empty_n;
wire    HwReg_width_c3_full_n;
wire   [10:0] HwReg_width_c3_dout;
wire   [2:0] HwReg_width_c3_num_data_valid;
wire   [2:0] HwReg_width_c3_fifo_cap;
wire    HwReg_width_c3_empty_n;
wire    HwReg_height_c5_full_n;
wire   [10:0] HwReg_height_c5_dout;
wire   [2:0] HwReg_height_c5_num_data_valid;
wire   [2:0] HwReg_height_c5_fifo_cap;
wire    HwReg_height_c5_empty_n;
wire    stream_csc_full_n;
wire   [23:0] stream_csc_dout;
wire   [4:0] stream_csc_num_data_valid;
wire   [4:0] stream_csc_fifo_cap;
wire    stream_csc_empty_n;
wire    HwReg_width_c_full_n;
wire   [10:0] HwReg_width_c_dout;
wire   [2:0] HwReg_width_c_num_data_valid;
wire   [2:0] HwReg_width_c_fifo_cap;
wire    HwReg_width_c_empty_n;
wire    HwReg_height_c_full_n;
wire   [10:0] HwReg_height_c_dout;
wire   [2:0] HwReg_height_c_num_data_valid;
wire   [2:0] HwReg_height_c_fifo_cap;
wire    HwReg_height_c_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_HwReg_height_c6_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_width_c4_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_ClipMax_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_ClampMin_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_BOffset_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_GOffset_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_ROffset_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_K33_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_K32_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_K31_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_K23_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_K22_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_K21_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_K13_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_K12_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_K11_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_OutVideoFormat_channel = 1'b0;
#0 ap_sync_reg_channel_write_HwReg_InVideoFormat_channel = 1'b0;
end

bd_19ea_csc_0_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .InVideoFormat(InVideoFormat),
    .OutVideoFormat(OutVideoFormat),
    .width(width),
    .height(height),
    .K11(K11),
    .K12(K12),
    .K13(K13),
    .K21(K21),
    .K22(K22),
    .K23(K23),
    .K31(K31),
    .K32(K32),
    .K33(K33),
    .ROffset(ROffset),
    .GOffset(GOffset),
    .BOffset(BOffset),
    .ClampMin(ClampMin),
    .ClipMax(ClipMax),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

bd_19ea_csc_0_Block_entry_split_proc Block_entry_split_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry_split_proc_U0_ap_start),
    .ap_done(Block_entry_split_proc_U0_ap_done),
    .ap_continue(Block_entry_split_proc_U0_ap_continue),
    .ap_idle(Block_entry_split_proc_U0_ap_idle),
    .ap_ready(Block_entry_split_proc_U0_ap_ready),
    .InVideoFormat(InVideoFormat),
    .OutVideoFormat(OutVideoFormat),
    .width(width),
    .height(height),
    .K11(K11),
    .K12(K12),
    .K13(K13),
    .K21(K21),
    .K22(K22),
    .K23(K23),
    .K31(K31),
    .K32(K32),
    .K33(K33),
    .ROffset(ROffset),
    .GOffset(GOffset),
    .BOffset(BOffset),
    .ClampMin(ClampMin),
    .ClipMax(ClipMax),
    .ap_return_0(Block_entry_split_proc_U0_ap_return_0),
    .ap_return_1(Block_entry_split_proc_U0_ap_return_1),
    .ap_return_2(Block_entry_split_proc_U0_ap_return_2),
    .ap_return_3(Block_entry_split_proc_U0_ap_return_3),
    .ap_return_4(Block_entry_split_proc_U0_ap_return_4),
    .ap_return_5(Block_entry_split_proc_U0_ap_return_5),
    .ap_return_6(Block_entry_split_proc_U0_ap_return_6),
    .ap_return_7(Block_entry_split_proc_U0_ap_return_7),
    .ap_return_8(Block_entry_split_proc_U0_ap_return_8),
    .ap_return_9(Block_entry_split_proc_U0_ap_return_9),
    .ap_return_10(Block_entry_split_proc_U0_ap_return_10),
    .ap_return_11(Block_entry_split_proc_U0_ap_return_11),
    .ap_return_12(Block_entry_split_proc_U0_ap_return_12),
    .ap_return_13(Block_entry_split_proc_U0_ap_return_13),
    .ap_return_14(Block_entry_split_proc_U0_ap_return_14),
    .ap_return_15(Block_entry_split_proc_U0_ap_return_15),
    .ap_return_16(Block_entry_split_proc_U0_ap_return_16),
    .ap_return_17(Block_entry_split_proc_U0_ap_return_17)
);

bd_19ea_csc_0_AXIvideo2MultiPixStream AXIvideo2MultiPixStream_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2MultiPixStream_U0_ap_start),
    .ap_done(AXIvideo2MultiPixStream_U0_ap_done),
    .ap_continue(AXIvideo2MultiPixStream_U0_ap_continue),
    .ap_idle(AXIvideo2MultiPixStream_U0_ap_idle),
    .ap_ready(AXIvideo2MultiPixStream_U0_ap_ready),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .s_axis_video_TREADY(AXIvideo2MultiPixStream_U0_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .stream_in_din(AXIvideo2MultiPixStream_U0_stream_in_din),
    .stream_in_num_data_valid(stream_in_num_data_valid),
    .stream_in_fifo_cap(stream_in_fifo_cap),
    .stream_in_full_n(stream_in_full_n),
    .stream_in_write(AXIvideo2MultiPixStream_U0_stream_in_write),
    .p_read(HwReg_height_c6_channel_dout),
    .p_read1(HwReg_width_c4_channel_dout),
    .p_read2(HwReg_InVideoFormat_channel_dout),
    .HwReg_width_c3_din(AXIvideo2MultiPixStream_U0_HwReg_width_c3_din),
    .HwReg_width_c3_num_data_valid(HwReg_width_c3_num_data_valid),
    .HwReg_width_c3_fifo_cap(HwReg_width_c3_fifo_cap),
    .HwReg_width_c3_full_n(HwReg_width_c3_full_n),
    .HwReg_width_c3_write(AXIvideo2MultiPixStream_U0_HwReg_width_c3_write),
    .HwReg_height_c5_din(AXIvideo2MultiPixStream_U0_HwReg_height_c5_din),
    .HwReg_height_c5_num_data_valid(HwReg_height_c5_num_data_valid),
    .HwReg_height_c5_fifo_cap(HwReg_height_c5_fifo_cap),
    .HwReg_height_c5_full_n(HwReg_height_c5_full_n),
    .HwReg_height_c5_write(AXIvideo2MultiPixStream_U0_HwReg_height_c5_write)
);

bd_19ea_csc_0_v_csc_core v_csc_core_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(v_csc_core_U0_ap_start),
    .ap_done(v_csc_core_U0_ap_done),
    .ap_continue(v_csc_core_U0_ap_continue),
    .ap_idle(v_csc_core_U0_ap_idle),
    .ap_ready(v_csc_core_U0_ap_ready),
    .stream_in_dout(stream_in_dout),
    .stream_in_num_data_valid(stream_in_num_data_valid),
    .stream_in_fifo_cap(stream_in_fifo_cap),
    .stream_in_empty_n(stream_in_empty_n),
    .stream_in_read(v_csc_core_U0_stream_in_read),
    .height_dout(HwReg_height_c5_dout),
    .height_num_data_valid(HwReg_height_c5_num_data_valid),
    .height_fifo_cap(HwReg_height_c5_fifo_cap),
    .height_empty_n(HwReg_height_c5_empty_n),
    .height_read(v_csc_core_U0_height_read),
    .width_dout(HwReg_width_c3_dout),
    .width_num_data_valid(HwReg_width_c3_num_data_valid),
    .width_fifo_cap(HwReg_width_c3_fifo_cap),
    .width_empty_n(HwReg_width_c3_empty_n),
    .width_read(v_csc_core_U0_width_read),
    .K11_read(HwReg_K11_channel_dout),
    .K12_read(HwReg_K12_channel_dout),
    .K13_read(HwReg_K13_channel_dout),
    .K21_read(HwReg_K21_channel_dout),
    .K22_read(HwReg_K22_channel_dout),
    .K23_read(HwReg_K23_channel_dout),
    .K31_read(HwReg_K31_channel_dout),
    .K32_read(HwReg_K32_channel_dout),
    .K33_read(HwReg_K33_channel_dout),
    .ROffset_read(HwReg_ROffset_channel_dout),
    .GOffset_read(HwReg_GOffset_channel_dout),
    .BOffset_read(HwReg_BOffset_channel_dout),
    .ClampMin_read(HwReg_ClampMin_channel_dout),
    .ClipMax_read(HwReg_ClipMax_channel_dout),
    .stream_csc_din(v_csc_core_U0_stream_csc_din),
    .stream_csc_num_data_valid(stream_csc_num_data_valid),
    .stream_csc_fifo_cap(stream_csc_fifo_cap),
    .stream_csc_full_n(stream_csc_full_n),
    .stream_csc_write(v_csc_core_U0_stream_csc_write),
    .HwReg_width_c_din(v_csc_core_U0_HwReg_width_c_din),
    .HwReg_width_c_num_data_valid(HwReg_width_c_num_data_valid),
    .HwReg_width_c_fifo_cap(HwReg_width_c_fifo_cap),
    .HwReg_width_c_full_n(HwReg_width_c_full_n),
    .HwReg_width_c_write(v_csc_core_U0_HwReg_width_c_write),
    .HwReg_height_c_din(v_csc_core_U0_HwReg_height_c_din),
    .HwReg_height_c_num_data_valid(HwReg_height_c_num_data_valid),
    .HwReg_height_c_fifo_cap(HwReg_height_c_fifo_cap),
    .HwReg_height_c_full_n(HwReg_height_c_full_n),
    .HwReg_height_c_write(v_csc_core_U0_HwReg_height_c_write)
);

bd_19ea_csc_0_MultiPixStream2AXIvideo MultiPixStream2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(MultiPixStream2AXIvideo_U0_ap_start),
    .ap_done(MultiPixStream2AXIvideo_U0_ap_done),
    .ap_continue(MultiPixStream2AXIvideo_U0_ap_continue),
    .ap_idle(MultiPixStream2AXIvideo_U0_ap_idle),
    .ap_ready(MultiPixStream2AXIvideo_U0_ap_ready),
    .stream_csc_dout(stream_csc_dout),
    .stream_csc_num_data_valid(stream_csc_num_data_valid),
    .stream_csc_fifo_cap(stream_csc_fifo_cap),
    .stream_csc_empty_n(stream_csc_empty_n),
    .stream_csc_read(MultiPixStream2AXIvideo_U0_stream_csc_read),
    .m_axis_video_TDATA(MultiPixStream2AXIvideo_U0_m_axis_video_TDATA),
    .m_axis_video_TVALID(MultiPixStream2AXIvideo_U0_m_axis_video_TVALID),
    .m_axis_video_TREADY(m_axis_video_TREADY),
    .m_axis_video_TKEEP(MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB),
    .m_axis_video_TUSER(MultiPixStream2AXIvideo_U0_m_axis_video_TUSER),
    .m_axis_video_TLAST(MultiPixStream2AXIvideo_U0_m_axis_video_TLAST),
    .m_axis_video_TID(MultiPixStream2AXIvideo_U0_m_axis_video_TID),
    .m_axis_video_TDEST(MultiPixStream2AXIvideo_U0_m_axis_video_TDEST),
    .Height_dout(HwReg_height_c_dout),
    .Height_num_data_valid(HwReg_height_c_num_data_valid),
    .Height_fifo_cap(HwReg_height_c_fifo_cap),
    .Height_empty_n(HwReg_height_c_empty_n),
    .Height_read(MultiPixStream2AXIvideo_U0_Height_read),
    .WidthOut_dout(HwReg_width_c_dout),
    .WidthOut_num_data_valid(HwReg_width_c_num_data_valid),
    .WidthOut_fifo_cap(HwReg_width_c_fifo_cap),
    .WidthOut_empty_n(HwReg_width_c_empty_n),
    .WidthOut_read(MultiPixStream2AXIvideo_U0_WidthOut_read),
    .p_read(HwReg_OutVideoFormat_channel_dout)
);

bd_19ea_csc_0_fifo_w8_d2_S HwReg_InVideoFormat_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_0),
    .if_full_n(HwReg_InVideoFormat_channel_full_n),
    .if_write(ap_channel_done_HwReg_InVideoFormat_channel),
    .if_dout(HwReg_InVideoFormat_channel_dout),
    .if_num_data_valid(HwReg_InVideoFormat_channel_num_data_valid),
    .if_fifo_cap(HwReg_InVideoFormat_channel_fifo_cap),
    .if_empty_n(HwReg_InVideoFormat_channel_empty_n),
    .if_read(AXIvideo2MultiPixStream_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w8_d4_S HwReg_OutVideoFormat_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_1),
    .if_full_n(HwReg_OutVideoFormat_channel_full_n),
    .if_write(ap_channel_done_HwReg_OutVideoFormat_channel),
    .if_dout(HwReg_OutVideoFormat_channel_dout),
    .if_num_data_valid(HwReg_OutVideoFormat_channel_num_data_valid),
    .if_fifo_cap(HwReg_OutVideoFormat_channel_fifo_cap),
    .if_empty_n(HwReg_OutVideoFormat_channel_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w16_d3_S HwReg_K11_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_2),
    .if_full_n(HwReg_K11_channel_full_n),
    .if_write(ap_channel_done_HwReg_K11_channel),
    .if_dout(HwReg_K11_channel_dout),
    .if_num_data_valid(HwReg_K11_channel_num_data_valid),
    .if_fifo_cap(HwReg_K11_channel_fifo_cap),
    .if_empty_n(HwReg_K11_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w16_d3_S HwReg_K12_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_3),
    .if_full_n(HwReg_K12_channel_full_n),
    .if_write(ap_channel_done_HwReg_K12_channel),
    .if_dout(HwReg_K12_channel_dout),
    .if_num_data_valid(HwReg_K12_channel_num_data_valid),
    .if_fifo_cap(HwReg_K12_channel_fifo_cap),
    .if_empty_n(HwReg_K12_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w16_d3_S HwReg_K13_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_4),
    .if_full_n(HwReg_K13_channel_full_n),
    .if_write(ap_channel_done_HwReg_K13_channel),
    .if_dout(HwReg_K13_channel_dout),
    .if_num_data_valid(HwReg_K13_channel_num_data_valid),
    .if_fifo_cap(HwReg_K13_channel_fifo_cap),
    .if_empty_n(HwReg_K13_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w16_d3_S HwReg_K21_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_5),
    .if_full_n(HwReg_K21_channel_full_n),
    .if_write(ap_channel_done_HwReg_K21_channel),
    .if_dout(HwReg_K21_channel_dout),
    .if_num_data_valid(HwReg_K21_channel_num_data_valid),
    .if_fifo_cap(HwReg_K21_channel_fifo_cap),
    .if_empty_n(HwReg_K21_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w16_d3_S HwReg_K22_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_6),
    .if_full_n(HwReg_K22_channel_full_n),
    .if_write(ap_channel_done_HwReg_K22_channel),
    .if_dout(HwReg_K22_channel_dout),
    .if_num_data_valid(HwReg_K22_channel_num_data_valid),
    .if_fifo_cap(HwReg_K22_channel_fifo_cap),
    .if_empty_n(HwReg_K22_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w16_d3_S HwReg_K23_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_7),
    .if_full_n(HwReg_K23_channel_full_n),
    .if_write(ap_channel_done_HwReg_K23_channel),
    .if_dout(HwReg_K23_channel_dout),
    .if_num_data_valid(HwReg_K23_channel_num_data_valid),
    .if_fifo_cap(HwReg_K23_channel_fifo_cap),
    .if_empty_n(HwReg_K23_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w16_d3_S HwReg_K31_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_8),
    .if_full_n(HwReg_K31_channel_full_n),
    .if_write(ap_channel_done_HwReg_K31_channel),
    .if_dout(HwReg_K31_channel_dout),
    .if_num_data_valid(HwReg_K31_channel_num_data_valid),
    .if_fifo_cap(HwReg_K31_channel_fifo_cap),
    .if_empty_n(HwReg_K31_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w16_d3_S HwReg_K32_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_9),
    .if_full_n(HwReg_K32_channel_full_n),
    .if_write(ap_channel_done_HwReg_K32_channel),
    .if_dout(HwReg_K32_channel_dout),
    .if_num_data_valid(HwReg_K32_channel_num_data_valid),
    .if_fifo_cap(HwReg_K32_channel_fifo_cap),
    .if_empty_n(HwReg_K32_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w16_d3_S HwReg_K33_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_10),
    .if_full_n(HwReg_K33_channel_full_n),
    .if_write(ap_channel_done_HwReg_K33_channel),
    .if_dout(HwReg_K33_channel_dout),
    .if_num_data_valid(HwReg_K33_channel_num_data_valid),
    .if_fifo_cap(HwReg_K33_channel_fifo_cap),
    .if_empty_n(HwReg_K33_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w10_d3_S HwReg_ROffset_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_11),
    .if_full_n(HwReg_ROffset_channel_full_n),
    .if_write(ap_channel_done_HwReg_ROffset_channel),
    .if_dout(HwReg_ROffset_channel_dout),
    .if_num_data_valid(HwReg_ROffset_channel_num_data_valid),
    .if_fifo_cap(HwReg_ROffset_channel_fifo_cap),
    .if_empty_n(HwReg_ROffset_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w10_d3_S HwReg_GOffset_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_12),
    .if_full_n(HwReg_GOffset_channel_full_n),
    .if_write(ap_channel_done_HwReg_GOffset_channel),
    .if_dout(HwReg_GOffset_channel_dout),
    .if_num_data_valid(HwReg_GOffset_channel_num_data_valid),
    .if_fifo_cap(HwReg_GOffset_channel_fifo_cap),
    .if_empty_n(HwReg_GOffset_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w10_d3_S HwReg_BOffset_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_13),
    .if_full_n(HwReg_BOffset_channel_full_n),
    .if_write(ap_channel_done_HwReg_BOffset_channel),
    .if_dout(HwReg_BOffset_channel_dout),
    .if_num_data_valid(HwReg_BOffset_channel_num_data_valid),
    .if_fifo_cap(HwReg_BOffset_channel_fifo_cap),
    .if_empty_n(HwReg_BOffset_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w8_d3_S HwReg_ClampMin_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_14),
    .if_full_n(HwReg_ClampMin_channel_full_n),
    .if_write(ap_channel_done_HwReg_ClampMin_channel),
    .if_dout(HwReg_ClampMin_channel_dout),
    .if_num_data_valid(HwReg_ClampMin_channel_num_data_valid),
    .if_fifo_cap(HwReg_ClampMin_channel_fifo_cap),
    .if_empty_n(HwReg_ClampMin_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w8_d3_S HwReg_ClipMax_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_15),
    .if_full_n(HwReg_ClipMax_channel_full_n),
    .if_write(ap_channel_done_HwReg_ClipMax_channel),
    .if_dout(HwReg_ClipMax_channel_dout),
    .if_num_data_valid(HwReg_ClipMax_channel_num_data_valid),
    .if_fifo_cap(HwReg_ClipMax_channel_fifo_cap),
    .if_empty_n(HwReg_ClipMax_channel_empty_n),
    .if_read(v_csc_core_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w11_d2_S HwReg_width_c4_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_16),
    .if_full_n(HwReg_width_c4_channel_full_n),
    .if_write(ap_channel_done_HwReg_width_c4_channel),
    .if_dout(HwReg_width_c4_channel_dout),
    .if_num_data_valid(HwReg_width_c4_channel_num_data_valid),
    .if_fifo_cap(HwReg_width_c4_channel_fifo_cap),
    .if_empty_n(HwReg_width_c4_channel_empty_n),
    .if_read(AXIvideo2MultiPixStream_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w11_d2_S HwReg_height_c6_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_split_proc_U0_ap_return_17),
    .if_full_n(HwReg_height_c6_channel_full_n),
    .if_write(ap_channel_done_HwReg_height_c6_channel),
    .if_dout(HwReg_height_c6_channel_dout),
    .if_num_data_valid(HwReg_height_c6_channel_num_data_valid),
    .if_fifo_cap(HwReg_height_c6_channel_fifo_cap),
    .if_empty_n(HwReg_height_c6_channel_empty_n),
    .if_read(AXIvideo2MultiPixStream_U0_ap_ready)
);

bd_19ea_csc_0_fifo_w24_d16_S stream_in_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_U0_stream_in_din),
    .if_full_n(stream_in_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_stream_in_write),
    .if_dout(stream_in_dout),
    .if_num_data_valid(stream_in_num_data_valid),
    .if_fifo_cap(stream_in_fifo_cap),
    .if_empty_n(stream_in_empty_n),
    .if_read(v_csc_core_U0_stream_in_read)
);

bd_19ea_csc_0_fifo_w11_d2_S HwReg_width_c3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_U0_HwReg_width_c3_din),
    .if_full_n(HwReg_width_c3_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_HwReg_width_c3_write),
    .if_dout(HwReg_width_c3_dout),
    .if_num_data_valid(HwReg_width_c3_num_data_valid),
    .if_fifo_cap(HwReg_width_c3_fifo_cap),
    .if_empty_n(HwReg_width_c3_empty_n),
    .if_read(v_csc_core_U0_width_read)
);

bd_19ea_csc_0_fifo_w11_d2_S HwReg_height_c5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2MultiPixStream_U0_HwReg_height_c5_din),
    .if_full_n(HwReg_height_c5_full_n),
    .if_write(AXIvideo2MultiPixStream_U0_HwReg_height_c5_write),
    .if_dout(HwReg_height_c5_dout),
    .if_num_data_valid(HwReg_height_c5_num_data_valid),
    .if_fifo_cap(HwReg_height_c5_fifo_cap),
    .if_empty_n(HwReg_height_c5_empty_n),
    .if_read(v_csc_core_U0_height_read)
);

bd_19ea_csc_0_fifo_w24_d16_S stream_csc_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_csc_core_U0_stream_csc_din),
    .if_full_n(stream_csc_full_n),
    .if_write(v_csc_core_U0_stream_csc_write),
    .if_dout(stream_csc_dout),
    .if_num_data_valid(stream_csc_num_data_valid),
    .if_fifo_cap(stream_csc_fifo_cap),
    .if_empty_n(stream_csc_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_stream_csc_read)
);

bd_19ea_csc_0_fifo_w11_d2_S HwReg_width_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_csc_core_U0_HwReg_width_c_din),
    .if_full_n(HwReg_width_c_full_n),
    .if_write(v_csc_core_U0_HwReg_width_c_write),
    .if_dout(HwReg_width_c_dout),
    .if_num_data_valid(HwReg_width_c_num_data_valid),
    .if_fifo_cap(HwReg_width_c_fifo_cap),
    .if_empty_n(HwReg_width_c_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_WidthOut_read)
);

bd_19ea_csc_0_fifo_w11_d2_S HwReg_height_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_csc_core_U0_HwReg_height_c_din),
    .if_full_n(HwReg_height_c_full_n),
    .if_write(v_csc_core_U0_HwReg_height_c_write),
    .if_dout(HwReg_height_c_dout),
    .if_num_data_valid(HwReg_height_c_num_data_valid),
    .if_fifo_cap(HwReg_height_c_fifo_cap),
    .if_empty_n(HwReg_height_c_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_Height_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_BOffset_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_BOffset_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_BOffset_channel <= ap_sync_channel_write_HwReg_BOffset_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_ClampMin_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_ClampMin_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_ClampMin_channel <= ap_sync_channel_write_HwReg_ClampMin_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_ClipMax_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_ClipMax_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_ClipMax_channel <= ap_sync_channel_write_HwReg_ClipMax_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_GOffset_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_GOffset_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_GOffset_channel <= ap_sync_channel_write_HwReg_GOffset_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_InVideoFormat_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_InVideoFormat_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_InVideoFormat_channel <= ap_sync_channel_write_HwReg_InVideoFormat_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_K11_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_K11_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_K11_channel <= ap_sync_channel_write_HwReg_K11_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_K12_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_K12_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_K12_channel <= ap_sync_channel_write_HwReg_K12_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_K13_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_K13_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_K13_channel <= ap_sync_channel_write_HwReg_K13_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_K21_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_K21_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_K21_channel <= ap_sync_channel_write_HwReg_K21_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_K22_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_K22_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_K22_channel <= ap_sync_channel_write_HwReg_K22_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_K23_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_K23_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_K23_channel <= ap_sync_channel_write_HwReg_K23_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_K31_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_K31_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_K31_channel <= ap_sync_channel_write_HwReg_K31_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_K32_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_K32_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_K32_channel <= ap_sync_channel_write_HwReg_K32_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_K33_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_K33_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_K33_channel <= ap_sync_channel_write_HwReg_K33_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_OutVideoFormat_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_OutVideoFormat_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_OutVideoFormat_channel <= ap_sync_channel_write_HwReg_OutVideoFormat_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_ROffset_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_ROffset_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_ROffset_channel <= ap_sync_channel_write_HwReg_ROffset_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_height_c6_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_height_c6_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_height_c6_channel <= ap_sync_channel_write_HwReg_height_c6_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_HwReg_width_c4_channel <= 1'b0;
    end else begin
        if (((Block_entry_split_proc_U0_ap_done & Block_entry_split_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_HwReg_width_c4_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_HwReg_width_c4_channel <= ap_sync_channel_write_HwReg_width_c4_channel;
        end
    end
end

assign AXIvideo2MultiPixStream_U0_ap_continue = 1'b1;

assign AXIvideo2MultiPixStream_U0_ap_start = (HwReg_width_c4_channel_empty_n & HwReg_height_c6_channel_empty_n & HwReg_InVideoFormat_channel_empty_n);

assign Block_entry_split_proc_U0_ap_continue = (ap_sync_channel_write_HwReg_width_c4_channel & ap_sync_channel_write_HwReg_height_c6_channel & ap_sync_channel_write_HwReg_ROffset_channel & ap_sync_channel_write_HwReg_OutVideoFormat_channel & ap_sync_channel_write_HwReg_K33_channel & ap_sync_channel_write_HwReg_K32_channel & ap_sync_channel_write_HwReg_K31_channel & ap_sync_channel_write_HwReg_K23_channel & ap_sync_channel_write_HwReg_K22_channel & ap_sync_channel_write_HwReg_K21_channel & ap_sync_channel_write_HwReg_K13_channel & ap_sync_channel_write_HwReg_K12_channel & ap_sync_channel_write_HwReg_K11_channel & ap_sync_channel_write_HwReg_InVideoFormat_channel & ap_sync_channel_write_HwReg_GOffset_channel & ap_sync_channel_write_HwReg_ClipMax_channel & ap_sync_channel_write_HwReg_ClampMin_channel & ap_sync_channel_write_HwReg_BOffset_channel);

assign Block_entry_split_proc_U0_ap_start = ap_start;

assign MultiPixStream2AXIvideo_U0_ap_continue = 1'b1;

assign MultiPixStream2AXIvideo_U0_ap_start = HwReg_OutVideoFormat_channel_empty_n;

assign ap_channel_done_HwReg_BOffset_channel = ((ap_sync_reg_channel_write_HwReg_BOffset_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_ClampMin_channel = ((ap_sync_reg_channel_write_HwReg_ClampMin_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_ClipMax_channel = ((ap_sync_reg_channel_write_HwReg_ClipMax_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_GOffset_channel = ((ap_sync_reg_channel_write_HwReg_GOffset_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_InVideoFormat_channel = ((ap_sync_reg_channel_write_HwReg_InVideoFormat_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_K11_channel = ((ap_sync_reg_channel_write_HwReg_K11_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_K12_channel = ((ap_sync_reg_channel_write_HwReg_K12_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_K13_channel = ((ap_sync_reg_channel_write_HwReg_K13_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_K21_channel = ((ap_sync_reg_channel_write_HwReg_K21_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_K22_channel = ((ap_sync_reg_channel_write_HwReg_K22_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_K23_channel = ((ap_sync_reg_channel_write_HwReg_K23_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_K31_channel = ((ap_sync_reg_channel_write_HwReg_K31_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_K32_channel = ((ap_sync_reg_channel_write_HwReg_K32_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_K33_channel = ((ap_sync_reg_channel_write_HwReg_K33_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_OutVideoFormat_channel = ((ap_sync_reg_channel_write_HwReg_OutVideoFormat_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_ROffset_channel = ((ap_sync_reg_channel_write_HwReg_ROffset_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_height_c6_channel = ((ap_sync_reg_channel_write_HwReg_height_c6_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_channel_done_HwReg_width_c4_channel = ((ap_sync_reg_channel_write_HwReg_width_c4_channel ^ 1'b1) & Block_entry_split_proc_U0_ap_done);

assign ap_done = MultiPixStream2AXIvideo_U0_ap_done;

assign ap_idle = (v_csc_core_U0_ap_idle & (1'b1 ^ HwReg_height_c6_channel_empty_n) & (1'b1 ^ HwReg_width_c4_channel_empty_n) & (1'b1 ^ HwReg_ClipMax_channel_empty_n) & (1'b1 ^ HwReg_ClampMin_channel_empty_n) & (1'b1 ^ HwReg_BOffset_channel_empty_n) & (1'b1 ^ HwReg_GOffset_channel_empty_n) & (1'b1 ^ HwReg_ROffset_channel_empty_n) & (1'b1 ^ HwReg_K33_channel_empty_n) & (1'b1 ^ HwReg_K32_channel_empty_n) & (1'b1 ^ HwReg_K31_channel_empty_n) & (1'b1 ^ HwReg_K23_channel_empty_n) & (1'b1 ^ HwReg_K22_channel_empty_n) & (1'b1 ^ HwReg_K21_channel_empty_n) & (1'b1 ^ HwReg_K13_channel_empty_n) & (1'b1 ^ HwReg_K12_channel_empty_n) & (1'b1 ^ HwReg_K11_channel_empty_n) & (1'b1 ^ HwReg_OutVideoFormat_channel_empty_n) & (1'b1 ^ HwReg_InVideoFormat_channel_empty_n) & MultiPixStream2AXIvideo_U0_ap_idle & Block_entry_split_proc_U0_ap_idle & AXIvideo2MultiPixStream_U0_ap_idle);

assign ap_ready = Block_entry_split_proc_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_channel_write_HwReg_BOffset_channel = ((ap_channel_done_HwReg_BOffset_channel & HwReg_BOffset_channel_full_n) | ap_sync_reg_channel_write_HwReg_BOffset_channel);

assign ap_sync_channel_write_HwReg_ClampMin_channel = ((ap_channel_done_HwReg_ClampMin_channel & HwReg_ClampMin_channel_full_n) | ap_sync_reg_channel_write_HwReg_ClampMin_channel);

assign ap_sync_channel_write_HwReg_ClipMax_channel = ((ap_channel_done_HwReg_ClipMax_channel & HwReg_ClipMax_channel_full_n) | ap_sync_reg_channel_write_HwReg_ClipMax_channel);

assign ap_sync_channel_write_HwReg_GOffset_channel = ((ap_channel_done_HwReg_GOffset_channel & HwReg_GOffset_channel_full_n) | ap_sync_reg_channel_write_HwReg_GOffset_channel);

assign ap_sync_channel_write_HwReg_InVideoFormat_channel = ((ap_channel_done_HwReg_InVideoFormat_channel & HwReg_InVideoFormat_channel_full_n) | ap_sync_reg_channel_write_HwReg_InVideoFormat_channel);

assign ap_sync_channel_write_HwReg_K11_channel = ((ap_channel_done_HwReg_K11_channel & HwReg_K11_channel_full_n) | ap_sync_reg_channel_write_HwReg_K11_channel);

assign ap_sync_channel_write_HwReg_K12_channel = ((ap_channel_done_HwReg_K12_channel & HwReg_K12_channel_full_n) | ap_sync_reg_channel_write_HwReg_K12_channel);

assign ap_sync_channel_write_HwReg_K13_channel = ((ap_channel_done_HwReg_K13_channel & HwReg_K13_channel_full_n) | ap_sync_reg_channel_write_HwReg_K13_channel);

assign ap_sync_channel_write_HwReg_K21_channel = ((ap_channel_done_HwReg_K21_channel & HwReg_K21_channel_full_n) | ap_sync_reg_channel_write_HwReg_K21_channel);

assign ap_sync_channel_write_HwReg_K22_channel = ((ap_channel_done_HwReg_K22_channel & HwReg_K22_channel_full_n) | ap_sync_reg_channel_write_HwReg_K22_channel);

assign ap_sync_channel_write_HwReg_K23_channel = ((ap_channel_done_HwReg_K23_channel & HwReg_K23_channel_full_n) | ap_sync_reg_channel_write_HwReg_K23_channel);

assign ap_sync_channel_write_HwReg_K31_channel = ((ap_channel_done_HwReg_K31_channel & HwReg_K31_channel_full_n) | ap_sync_reg_channel_write_HwReg_K31_channel);

assign ap_sync_channel_write_HwReg_K32_channel = ((ap_channel_done_HwReg_K32_channel & HwReg_K32_channel_full_n) | ap_sync_reg_channel_write_HwReg_K32_channel);

assign ap_sync_channel_write_HwReg_K33_channel = ((ap_channel_done_HwReg_K33_channel & HwReg_K33_channel_full_n) | ap_sync_reg_channel_write_HwReg_K33_channel);

assign ap_sync_channel_write_HwReg_OutVideoFormat_channel = ((ap_channel_done_HwReg_OutVideoFormat_channel & HwReg_OutVideoFormat_channel_full_n) | ap_sync_reg_channel_write_HwReg_OutVideoFormat_channel);

assign ap_sync_channel_write_HwReg_ROffset_channel = ((ap_channel_done_HwReg_ROffset_channel & HwReg_ROffset_channel_full_n) | ap_sync_reg_channel_write_HwReg_ROffset_channel);

assign ap_sync_channel_write_HwReg_height_c6_channel = ((ap_channel_done_HwReg_height_c6_channel & HwReg_height_c6_channel_full_n) | ap_sync_reg_channel_write_HwReg_height_c6_channel);

assign ap_sync_channel_write_HwReg_width_c4_channel = ((ap_channel_done_HwReg_width_c4_channel & HwReg_width_c4_channel_full_n) | ap_sync_reg_channel_write_HwReg_width_c4_channel);

assign m_axis_video_TDATA = MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;

assign m_axis_video_TDEST = MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;

assign m_axis_video_TID = MultiPixStream2AXIvideo_U0_m_axis_video_TID;

assign m_axis_video_TKEEP = MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;

assign m_axis_video_TLAST = MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;

assign m_axis_video_TSTRB = MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;

assign m_axis_video_TUSER = MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;

assign m_axis_video_TVALID = MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;

assign s_axis_video_TREADY = AXIvideo2MultiPixStream_U0_s_axis_video_TREADY;

assign v_csc_core_U0_ap_continue = 1'b1;

assign v_csc_core_U0_ap_start = (HwReg_ROffset_channel_empty_n & HwReg_K33_channel_empty_n & HwReg_K32_channel_empty_n & HwReg_K31_channel_empty_n & HwReg_K23_channel_empty_n & HwReg_K22_channel_empty_n & HwReg_K21_channel_empty_n & HwReg_K13_channel_empty_n & HwReg_K12_channel_empty_n & HwReg_K11_channel_empty_n & HwReg_GOffset_channel_empty_n & HwReg_ClipMax_channel_empty_n & HwReg_ClampMin_channel_empty_n & HwReg_BOffset_channel_empty_n);


reg find_df_deadlock = 0;
// synthesis translate_off
`include "bd_19ea_csc_0_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "bd_19ea_csc_0_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //bd_19ea_csc_0_v_csc

