-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_19ea_csc_0_v_csc_core is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_in_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    stream_in_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_in_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_in_empty_n : IN STD_LOGIC;
    stream_in_read : OUT STD_LOGIC;
    height_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    height_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    height_empty_n : IN STD_LOGIC;
    height_read : OUT STD_LOGIC;
    width_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    width_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_empty_n : IN STD_LOGIC;
    width_read : OUT STD_LOGIC;
    K11_read : IN STD_LOGIC_VECTOR (15 downto 0);
    K12_read : IN STD_LOGIC_VECTOR (15 downto 0);
    K13_read : IN STD_LOGIC_VECTOR (15 downto 0);
    K21_read : IN STD_LOGIC_VECTOR (15 downto 0);
    K22_read : IN STD_LOGIC_VECTOR (15 downto 0);
    K23_read : IN STD_LOGIC_VECTOR (15 downto 0);
    K31_read : IN STD_LOGIC_VECTOR (15 downto 0);
    K32_read : IN STD_LOGIC_VECTOR (15 downto 0);
    K33_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ROffset_read : IN STD_LOGIC_VECTOR (9 downto 0);
    GOffset_read : IN STD_LOGIC_VECTOR (9 downto 0);
    BOffset_read : IN STD_LOGIC_VECTOR (9 downto 0);
    ClampMin_read : IN STD_LOGIC_VECTOR (7 downto 0);
    ClipMax_read : IN STD_LOGIC_VECTOR (7 downto 0);
    stream_csc_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    stream_csc_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_csc_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_csc_full_n : IN STD_LOGIC;
    stream_csc_write : OUT STD_LOGIC;
    HwReg_width_c_din : OUT STD_LOGIC_VECTOR (10 downto 0);
    HwReg_width_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_width_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_width_c_full_n : IN STD_LOGIC;
    HwReg_width_c_write : OUT STD_LOGIC;
    HwReg_height_c_din : OUT STD_LOGIC_VECTOR (10 downto 0);
    HwReg_height_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_height_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_height_c_full_n : IN STD_LOGIC;
    HwReg_height_c_write : OUT STD_LOGIC );
end;


architecture behav of bd_19ea_csc_0_v_csc_core is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv12_800 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal height_blk_n : STD_LOGIC;
    signal width_blk_n : STD_LOGIC;
    signal HwReg_width_c_blk_n : STD_LOGIC;
    signal HwReg_height_c_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal thr_add_fu_233_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal thr_add_reg_365 : STD_LOGIC_VECTOR (21 downto 0);
    signal thr_add1_fu_241_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal thr_add1_reg_370 : STD_LOGIC_VECTOR (21 downto 0);
    signal thr_add3_fu_249_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal thr_add3_reg_375 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln134_fu_261_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln134_reg_380 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln134_1_fu_271_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln134_1_reg_385 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start : STD_LOGIC;
    signal grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_done : STD_LOGIC;
    signal grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_idle : STD_LOGIC;
    signal grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_ready : STD_LOGIC;
    signal grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_in_read : STD_LOGIC;
    signal grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_csc_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_csc_write : STD_LOGIC;
    signal grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln134_fu_285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal y_fu_92 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal y_3_fu_290_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal height_read_local : STD_LOGIC;
    signal HwReg_height_c_write_local : STD_LOGIC;
    signal width_read_local : STD_LOGIC;
    signal HwReg_width_c_write_local : STD_LOGIC;
    signal loopWidth_cast_fu_257_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal height_load_cast_fu_267_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bd_19ea_csc_0_v_csc_core_Pipeline_VITIS_LOOP_136_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_in_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        stream_in_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_in_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_in_empty_n : IN STD_LOGIC;
        stream_in_read : OUT STD_LOGIC;
        stream_csc_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        stream_csc_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_csc_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_csc_full_n : IN STD_LOGIC;
        stream_csc_write : OUT STD_LOGIC;
        add_ln134 : IN STD_LOGIC_VECTOR (11 downto 0);
        K12_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        K13_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        K11_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        thr_add131_cast : IN STD_LOGIC_VECTOR (21 downto 0);
        K22_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        K23_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        K21_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        thr_add62_cast : IN STD_LOGIC_VECTOR (21 downto 0);
        K32_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        K33_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        K31_load_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln134 : IN STD_LOGIC_VECTOR (21 downto 0);
        p_read12_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read13_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        ClipMax_read : IN STD_LOGIC_VECTOR (7 downto 0);
        ClampMin_read : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208 : component bd_19ea_csc_0_v_csc_core_Pipeline_VITIS_LOOP_136_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start,
        ap_done => grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_done,
        ap_idle => grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_idle,
        ap_ready => grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_ready,
        stream_in_dout => stream_in_dout,
        stream_in_num_data_valid => ap_const_lv5_0,
        stream_in_fifo_cap => ap_const_lv5_0,
        stream_in_empty_n => stream_in_empty_n,
        stream_in_read => grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_in_read,
        stream_csc_din => grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_csc_din,
        stream_csc_num_data_valid => ap_const_lv5_0,
        stream_csc_fifo_cap => ap_const_lv5_0,
        stream_csc_full_n => stream_csc_full_n,
        stream_csc_write => grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_csc_write,
        add_ln134 => add_ln134_reg_380,
        K12_load_cast => K12_read,
        K13_load_cast => K13_read,
        K11_load_cast => K11_read,
        thr_add131_cast => thr_add_reg_365,
        K22_load_cast => K22_read,
        K23_load_cast => K23_read,
        K21_load_cast => K21_read,
        thr_add62_cast => thr_add1_reg_370,
        K32_load_cast => K32_read,
        K33_load_cast => K33_read,
        K31_load_cast => K31_read,
        sext_ln134 => thr_add3_reg_375,
        p_read12_cast => ClampMin_read,
        p_read13_cast => ClipMax_read,
        ClipMax_read => ClipMax_read,
        ClampMin_read => ClampMin_read);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln134_fu_285_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln134_fu_285_p2 = ap_const_lv1_0))) then 
                    grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_ready = ap_const_logic_1)) then 
                    grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_92 <= ap_const_lv12_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln134_fu_285_p2 = ap_const_lv1_0))) then 
                y_fu_92 <= y_3_fu_290_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                add_ln134_1_reg_385 <= add_ln134_1_fu_271_p2;
                add_ln134_reg_380 <= add_ln134_fu_261_p2;
                    thr_add1_reg_370(21 downto 12) <= thr_add1_fu_241_p3(21 downto 12);
                    thr_add3_reg_375(21 downto 12) <= thr_add3_fu_249_p3(21 downto 12);
                    thr_add_reg_365(21 downto 12) <= thr_add_fu_233_p3(21 downto 12);
            end if;
        end if;
    end process;
    thr_add_reg_365(11 downto 0) <= "100000000000";
    thr_add1_reg_370(11 downto 0) <= "100000000000";
    thr_add3_reg_375(11 downto 0) <= "100000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_done, ap_CS_fsm_state2, icmp_ln134_fu_285_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln134_fu_285_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;

    HwReg_height_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_height_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_height_c_blk_n <= HwReg_height_c_full_n;
        else 
            HwReg_height_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_height_c_din <= height_dout;
    HwReg_height_c_write <= HwReg_height_c_write_local;

    HwReg_height_c_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_height_c_write_local <= ap_const_logic_1;
        else 
            HwReg_height_c_write_local <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_width_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_width_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_width_c_blk_n <= HwReg_width_c_full_n;
        else 
            HwReg_width_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_width_c_din <= width_dout;
    HwReg_width_c_write <= HwReg_width_c_write_local;

    HwReg_width_c_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_width_c_write_local <= ap_const_logic_1;
        else 
            HwReg_width_c_write_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln134_1_fu_271_p2 <= std_logic_vector(unsigned(height_load_cast_fu_267_p1) + unsigned(ap_const_lv12_1));
    add_ln134_fu_261_p2 <= std_logic_vector(unsigned(loopWidth_cast_fu_257_p1) + unsigned(ap_const_lv12_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_done)
    begin
        if ((grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, height_empty_n, width_empty_n, HwReg_width_c_full_n, HwReg_height_c_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (width_empty_n = ap_const_logic_0) or (height_empty_n = ap_const_logic_0) or (ap_const_logic_0 = HwReg_height_c_full_n) or (ap_const_logic_0 = HwReg_width_c_full_n) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln134_fu_285_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln134_fu_285_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln134_fu_285_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln134_fu_285_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start <= grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_ap_start_reg;

    height_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_blk_n <= height_empty_n;
        else 
            height_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    height_load_cast_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height_dout),12));
    height_read <= height_read_local;

    height_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_read_local <= ap_const_logic_1;
        else 
            height_read_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln134_fu_285_p2 <= "1" when (y_fu_92 = add_ln134_1_reg_385) else "0";
    loopWidth_cast_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width_dout),12));
    stream_csc_din <= grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_csc_din;

    stream_csc_write_assign_proc : process(grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_csc_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            stream_csc_write <= grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_csc_write;
        else 
            stream_csc_write <= ap_const_logic_0;
        end if; 
    end process;


    stream_in_read_assign_proc : process(grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_in_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            stream_in_read <= grp_v_csc_core_Pipeline_VITIS_LOOP_136_2_fu_208_stream_in_read;
        else 
            stream_in_read <= ap_const_logic_0;
        end if; 
    end process;

    thr_add1_fu_241_p3 <= (GOffset_read & ap_const_lv12_800);
    thr_add3_fu_249_p3 <= (BOffset_read & ap_const_lv12_800);
    thr_add_fu_233_p3 <= (ROffset_read & ap_const_lv12_800);

    width_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_blk_n <= width_empty_n;
        else 
            width_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    width_read <= width_read_local;

    width_read_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_read_local <= ap_const_logic_1;
        else 
            width_read_local <= ap_const_logic_0;
        end if; 
    end process;

    y_3_fu_290_p2 <= std_logic_vector(unsigned(y_fu_92) + unsigned(ap_const_lv12_1));
end behav;
