

set_false_path -from [get_cells CTRL_s_axi_U/int_InVideoFormat_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_OutVideoFormat_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_width_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_height_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_K11_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_K12_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_K13_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_K21_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_K22_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_K23_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_K31_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_K32_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_K33_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_ROffset_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_GOffset_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_BOffset_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_ClampMin_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_ClipMax_reg[*]]
